### ISSUE TITLE
Review use of `secondary-selection` face to highlight block

### ISSUE THREAD

**Issue by protesilaos** [nobiot/org-transclusion#1]
Thank you for sharing your work! I think the `secondary-selection` face, [currently used on line 142](https://github.com/nobiot/org-transclusion/blob/85632d9f657837e5ef9e44db14e0063090e28084/org-transclusion.el#L142), does not always work well for areas that can/should be edited.

An alternative would be to define a face and use that instead. The benefit is that it makes it possible for other themes (or users in their configs) to change styles.  This diff shows an example. It defines only a background colour (one for light, another for dark), which means that it should not change the text colours used in the block.

```diff
 org-transclusion.el | 11 ++++++++++-
 1 file changed, 10 insertions(+), 1 deletion(-)

diff --git a/org-transclusion.el b/org-transclusion.el
index 576ee9c..970ff05 100644
--- a/org-transclusion.el
+++ b/org-transclusion.el
@@ -34,6 +34,15 @@
 (require 'org-element)
 (require 'org-id)
 
+;;-----------------------------------------------------------------------------
+;; Faces
+(defface org-transclusion-block
+  '((((class color) (min-colors 88) (background light))
+     :background "#f0f0f0" :extend t)
+    (((class color) (min-colors 88) (background dark))
+     :background "#181a20" :extend t))
+  "Face for transcluded block.")
+
 ;;-----------------------------------------------------------------------------
 ;; Variables
 ;; Most of these should be defcustom
@@ -139,7 +148,7 @@ Assume the RAW-LINK is a valid tranclusion link."
       ;; ensures that the location of overlay is not shifted for the remove
       ;; function.when a new line is added back to allow space for the original
       ;; tranclusion link for the remove function.
-      (overlay-put ov 'face 'secondary-selection)
+      (overlay-put ov 'face 'org-transclusion-block)
       (overlay-put ov 'path path)
       (overlay-put ov 'tc-src-buf buf)
       (overlay-put ov 'tc-src-marker marker)
``` 

Feel free to adapt this to your particular needs.  It is just an idea.

**Comment by nobiot** [comment]
Thank you! I would just take the change as is, if you don’t mind sensing a PR. Otherwise, I’ll put it in my local, test it and merge.

**Comment by protesilaos** [comment]
> Otherwise, I’ll put it in my local, test it and merge.

I think it is better you do that. My intention was to show how a custom face can be used. You may find other examples with `M-x find-library` and then search for `faces`.

**Comment by nobiot** [comment]
No worries. Thank you for the diff and input — especially the dark/light themes and their impact on legibility. I’ll see how far I can get :)

**Comment by protesilaos** [comment]
> I’ll see how far I can get :)

Feel free to contact me if you need help with faces and the like.

**Comment by nobiot** [comment]
#39 merges Prot's code (with some adjustment) to the main branch.
Thank you, @protesilaos :)
