### ISSUE TITLE
Transclusion for a paragraph of Org file copies beyond the specified paragraph

### ISSUE THREAD

**Issue by nobiot** [nobiot/org-transclusion#102]
Offshoot from #101 
https://github.com/nobiot/org-transclusion/issues/101#issuecomment-960552147

@oatmealm wrote:
 
> 9.5 but now org-transclusion seem to include the complete file from the > point of the target.

> Link style:
```
#+transclude: [[file:~/Nextcloud/roam/references/ocr/כהן1996.org::תרבות_ברק]] 
```
> This is the complete paragraph, which has line breaks before and after.
```
במיוחד להקשר ההיסטורי, וברצוננו להיעזר אפוא בהגדרתו של ההיסטוריון [[id:98da41c4-2b22-4d1b-b89e-4dc8f2bec308][פ' ברק]]
(‏Burke), בספרו על התרבות העממית של ראשית העת החדשה באירופה: <<תרבות_ברק>> 'תרבות
היא ‏מערכת של משמעויות, גישות וערכים משותפים, והצורות הסמליות (מופעים, חפצים)‎
שבהם היא מתבטאת או מתגלמת'.[fn:4]
```

**Comment by oatmealm** [comment]
Thanks! Works for me. Repeating myself probably, but thanks again. This package is incredibly useful.

**Comment by nobiot** [comment]
@oatmealm thank you for confirming and your kind words :)
