### ISSUE TITLE
Integration with org task management ecosystem?

### ISSUE THREAD

**Issue by dev590t** [nobiot/org-transclusion#108]
[This post indicates the limit of expressivity of org mode to be a good task management.](https://www.reddit.com/r/orgmode/comments/qyrtdn/the_limit_of_org_mode_to_become_the_ideal_task/)
transclusion can be the solution if it can integrate seemless a external task E to a task T as its subtask such all function org  can run on the external task E as E is subtask of T.
I have test it, but it seem org-transclusion don't support very well such feature
```
* project 1
** TODO task 1
:PROPERTIES:
:ID:       a5efaa82-f97c-4367-9b88-025d3d96ed40
:Effort:   3
:END:
* project 2 [0/0]
#+COLUMNS: %40ITEM(Task) %17Effort(Estimated Effort){:} %CLOCKSUM   
#+transclude: [[id:a5efaa82-f97c-4367-9b88-025d3d96ed40][Bertrand Russell]] 
** DONE task 2
CLOSED: [2021-12-11 Sat 23:14]
:PROPERTIES:
:Effort:   4
:END:
```
`M-x org-transclusion-add-all`
`M-x org-columns` => I get the error `(void-function backtrace-get-frames)`
I expect the total effort of project 2 is sum of effort of task 1 and 2. 

Did org-transclusion intent to cover such feature?

**Comment by nobiot** [comment]
@dev590t 

It looks to work on my end. See the image below.
I just copy-and-pasted your example.

![Screenshot from 2021-12-12 20-50-04](https://user-images.githubusercontent.com/12507865/145727331-1dfe7028-abe1-44fe-af57-9211b2b6b187.png)

One thing is that `property-drawer` is excluded from transclusion by default. You can adjust this behaviour by setting user option `org-transclusion-exclude-elements` as done at the bottom part in the screen shot.

This is not the cause of the error, though. I think it's not caused by Org-transcusion.
Without property drawer, I don't get the error message you report; only an incorrect summary (0 + 4 = 4).

**Comment by dev590t** [comment]
You are right. I have retry to run emacs in a container with only Org-transcusion package. That run perfectly.
So the issue should from my doom emacs environment.

**Comment by dev590t** [comment]
Thank for this super library. I think all user of org task management should know it. It allow pass tree structure of org document to a graph structure, that is much better for task management

**Comment by nobiot** [comment]
> Thanks for this super library. I think all user of org task management should know it. It allow pass tree structure of org document to a graph structure, that is much better for task management

Thank you 🙏 
I like how you characterize Org-transclusion with tree/network structures. I never thought it this way.

I’m in the process of publishing it on ELPA, so it will be easier for others to install and use Org-transclusion. I will consider adding your use case to README and other places where I explain actual examples :)

**Comment by dev590t** [comment]
You can check this posts

The limit of org mode to become the ideal task management:
https://www.reddit.com/r/orgmode/comments/qyrtdn/the_limit_of_org_mode_to_become_the_ideal_task/

transclusion is better solution to express graph logic than org-roam because it can integrate seemless to org task management ecosystem:
https://www.reddit.com/r/orgmode/comments/qyrtdn/comment/hligb5g/?utm_source=share&utm_medium=web2x&context=3

Some attempt to create a task management with graph paradigm:
https://www.reddit.com/r/emacs/comments/qyajk9/any_package_for_querying_or_visualizing_orgedna/hljujtm/?utm_source=share&utm_medium=web2x&context=3

org-transclusion is a very promise project that can concurrence to org-roam to express the graph logic of headline if it can integrate seemless to org ecosystem. It can revolutionize the expressivity of org document.

Currently we haven't tutorial that combine org-transclusion and task management workflow. I think that could be interest many user of org mode, and give to org-transclusion many popularity.

**Comment by nobiot** [comment]
@dev590t 
Thanks for the links. The initiative TeMPOraL_PL is proposing is indeed interesting.

I don't think I will implement graph DB in Org-transclusion -- I would like to keep dependencies minimal. At the moment, it requires only certain versions of Org and Emacs, no external dependencies. 

As for tutorials on task management workflows, I am not the right person to create such material I don't use Org as a task and project management tool myself -- a simple TODO list is enough for me.

Having said all this, I am open for suggestions and will be happy to assist if Org-transclusion and my experience can be of help in any way.
