### ISSUE TITLE
Allow adding #+name, #+caption etc before #+transclude keyword

### ISSUE THREAD

**Issue by Jason-S-Ross** [nobiot/org-transclusion#115]
It would be nice to be able to name transcluded code blocks e.g. to tag their outputs. For instance, here's a pattern I use a lot:

```
#+name: foo-src
#+begin_src python 
import matplotlib.pyplot as plt
plt.plot(range(10), [x**2 for x in range(10)])
#+end_src

#+name: foo-fig
#+results: foo-src
[[fig]]

Refer to figure [[foo-fig]] for what a parabola looks like
```

I stick a `#+name` tag on the results, but in order to do that, I need the source to be named as well. But when I toggle `org-transclusion-mode`, my header arguments get gobbled up.

**Comment by nobiot** [comment]
Thank you for reporting this.

PR #116 should address the issue -- refer to the Figure 1 and 2 below. Please correct me if my understanding is not correct.
if you have time and able to do so, I'd appreciate if you could test the [branch.](https://github.com/nobiot/org-transclusion/tree/fix/affiliated-keyword)

I would like to keep it in a [fix branch ](https://github.com/nobiot/org-transclusion/tree/fix/affiliated-keyword) for a week or so to see if I have missed anything before merging it to the main.

**Figure 1.** Before transclusion -- notice the "#+name" before the transclusion
![Screenshot from 2022-01-04 22-41-11](https://user-images.githubusercontent.com/12507865/148128603-71143a81-5481-4afc-8c05-7a8a6d880f1e.png)
branch.
**Figure 2.** After transclusion
![Screenshot from 2022-01-04 22-41-20](https://user-images.githubusercontent.com/12507865/148128606-496dfeac-636f-478d-b81e-6934b8cd5b51.png)

**Comment by nobiot** [comment]
> I would like to keep it in a fix branch for a week or so to see if I have missed anything before merging it to the main.

Taking back what I said. Sorry if this caused confusion. I have merged the PR to the main so that it will be reflected ELPA-devel. I'll leave it there for a week or so (probably until the end of weekend this week) and bump up the version to get it reflected in ELPA.

@Jason-S-Ross I would still appreciate if you could try the fix -- it's fine if you don't have time or are not able to do this. 
Thank you.

**Comment by Jason-S-Ross** [comment]
It looks like the fix works! Thank you!

**Comment by nobiot** [comment]
Jason Ross ***@***.***> writes:

> It looks like the fix works! Thank you!

Thank you for confirming :)
