### ISSUE TITLE
Syntax Highlighting in Blocks

### ISSUE THREAD

**Issue by joshcho** [nobiot/org-transclusion#130]
Not sure if intended, but in special blocks (e.g. `#+begin_theorem`), syntax highlighting does not work for transcluded blocks. My specific use case is I like to have `#+begin_notes` in my org documents when I want a block I can collapse.

**Comment by nobiot** [comment]
How can I reproduce this? I don't use `#+begin_notes` and don't know how to turn on syntax highlighting.
The syntax highlighting seems to work with `#+begin_src`, so I don't know why it wouldn't work for others.
