### ISSUE TITLE
Transclusions in plain/numbered lists break their flow

### ISSUE THREAD

**Issue by alecigne** [nobiot/org-transclusion#131]
Hi,

First of all, thank you very much for your work on `org-transclusion`. This is a step closer to perfection in the Org ecosystem!

I am sorry in advance if I missed some documentation about the issue below but I am quite new to this package.

### Environment

- Emacs 27.1
- Vanilla config - I simply installed `org-transclusion` for this test.
- No special mode activated - especially not `org-indent-mode` for what it's worth :smiley: 
  ```
  Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
  Blink-Cursor Electric-Indent File-Name-Shadow Font-Lock Global-Eldoc
  Global-Font-Lock Line-Number Menu-Bar Mouse-Wheel Org-Transclusion
  Shell-Dirtrack Tool-Bar Tooltip Transient-Mark
  ```

### Context

I often write plain lists in Org mode with multiple "paragraphs", like this:

```
* Level one

1. First item

   Text associated with the first item. <--- problematic line

2. Second item

* Level two
```

Org understands that the text below the first item is associated with it, notably during an export. Here is an ASCII export:

```
1 Level one
===========

  1. First item

     Text associated with the first item.

  2. Second item


2 Level two
===========
```

### Problem

However, this doesn't seem to work with transclusions. If I start from this Org file:

```
* Level one

1. First item

   Text associated with the first item.

   #+transclude: [[file:paragraph.txt][link]] 

2. Second item

* Level two
```

...`org-transclusion-add` will produce this text in the Emacs buffer:

```
* Level one

1. First item

   Text associated with the first item.

Text associated to the first item.

2. Second item

* Level two
```

And here is an ASCII export:

```
1 Level one
===========

  1. First item

     Text associated with the first item.

  Text associated to the first item.

  1. Second item


2 Level two
===========
```

As you can see the text is not indented anymore and the "logical" connection between the item and its continuation is lost. In the case of numbered lists, as here, this also breaks the numbering, which is expected in Org-mode when the line above is not indented.

### Expectation

It would be better if the transclusion was indented so that plain/numbered lists are displayed correctly within Emacs and in an export. Org input:

```
* Level one

1. First item

   Text associated with the first item.

   #+transclude: [[file:paragraph.txt][link]] 

2. Second item

* Level two
```

Output:

```
* Level one

1. First item

   Text associated with the first item.

   Text associated with the first item.

2. Second item

* Level two
```

Thank you!

**Comment by nobiot** [comment]
@alecigne Thank you for your precise and contained report.

> * especially not `org-indent-mode` for what it's worth
Really appreciate this :1st_place_medal: :smile: 

It looks like we need to adjust  function `org-transclusion-content-format`. Need some time to see what can be done.

Thanks again!

**Comment by nobiot** [comment]
Fix has been merged with the main. You can either try the new commit or wait for ELPA-devel to run the next sync with GitHub (I believe it's hourly). 

I'd appreciate it if you could try the fix before I bump up the version for ELPA -- the code should not affect non-Org files but I'd also appreciate more pairs of eyes testing to see if the fix didn't break anything....

Thanks!

**Comment by alecigne** [comment]
Hi @nobiot,

Wow, that was fast :smiley: I tried the `main` branch in the above conditions (transclusion of non-Org files in Vanilla Emacs) and everything seems to be in order :+1: Nothing seems to be broken in my current projects either.

Just so we are on the same page: even if it was not my original use case, when transcluding Org files, the bug is still present. As I understand, this is a more general bug and it is harder to fix, right?

Anyway - thank you for your reactivity!

**Comment by nobiot** [comment]
@alecigne Thank you for confirming.

Yes, I localized the effect of the fix to non-Org files only. I think for Org files we will need more considerations of different cases. 

This is mainly because transcluding Org files can bring in different "elements". For example, bringing in a whole headline or file. In these cases, it would break the structure of the document if we indent the whole headline or file (the stars "*" for headline needs to be in the beginning of the line with no indentation, for example).

For text files, I think it's much safer to treat them to be all "paragraphs" -- Markdown and other markup files might be exception but I don't believe there is a real use case to use Org, Org-transclusion, and Markdown together.

I think the indentation for Org files would need to be restricted only for paragraph transclusion. But I think because of different elements can come in, I would like to be more careful with Org files.

If you have a real use case, I would like to know about it for more consideration. 

Thank you :)

**Comment by alecigne** [comment]
@nobiot Thank you for the details, it is more clear now.

> If you have a real use case, I would like to know about it for more consideration.

My use case was simply to transclude source files (Lisp, Java...) - so as far as I am concerned this issue can be marked as resolved. Thanks again!

**Comment by nobiot** [comment]
@alecigne Thank you. Let me know if you encounter issues (perhaps by opening another issue). Thanks :)
