### ISSUE TITLE
Should a transcluded link count as a backlink for org-roam?

### ISSUE THREAD

**Issue by jeremyf** [nobiot/org-transclusion#136]
I started exploring using org-transclusion, and it's rather amazing.  So thank you.

One question I have for @noboit is around the following scenario:

```gherkin
Given the nodes A and B,
When node B has a transclude entry for node A
Then the org-roam backlinks for A should include B
```

When I was first working with transclusions, I assumed that A's backlinks would include B.  However, that does not appear to be the case.

Then I started thinking more about it, and wonder if it should be a separate section in the backlinks.  The transclusions aren't quite links, but instead "embeds" and perhaps shouldn't register as that.

To resolve my desire for the backlink, I have have chosen the following structure:

```
:PROPERTIES:
:ID: node-b
:END:
#+title: Node B

* [[id:node-a][Title of Node A]]

#+transclude [[id:node-a][Title of Node A]]
```

While the "duplication" of [Title of Node A] is a bit of mental static on my programmer brain, it seems to resolve two things:

1) I am not relying on moving the `* Title of Node A` into node A.
2) I get backlinks

However, I'd love to know if the absence of backlinks is a design decision.

Again, thank you for this great package.  I'm looking forward to writing more about it as I further test the feature.

**Comment by jeremyf** [comment]
@nobiot Thank you for your insight.  I will (as time permits) file an issue on org-roam and see if I can even patch it.  I'll keep this issue open as a "tracking" issue.

**Comment by nobiot** [comment]
Actually, it's just customizing.

Have a look at the default value of `org-roam-db-extra-links-exclude-keys`
Transclusion is deliberately excluded. Just removed the second element, and it should work.

```
Original value was 
((node-property "ROAM_REFS")
 (keyword "transclude"))
```

**Comment by jeremyf** [comment]
Thank you for the follow-up.  Closing the issue.
