### ISSUE TITLE
Doesn't seem to support roam-2 files via ID links

### ISSUE THREAD

**Issue by shader** [nobiot/org-transclusion#139]
If I have a roam note stored as a file (e.g., with PROPERTIES at the beginning specifying the ID and a #+title), then org-transclusion does not find any content associated with the ID.

It works if I add an ID to a headline in the same file, and link to that instead, but not when I link to the file as a whole.

**Comment by nobiot** [comment]
You probably have the same issue with this:
https://github.com/nobiot/org-transclusion/issues/138

**Comment by nobiot** [comment]
I’m closing this issue. Let me know and feel free to reopen if the reported issue is not the same as suggested.
