### ISSUE TITLE
Transclusion at heading level by adding up the source + destination indentations

### ISSUE THREAD

**Issue by lytex** [nobiot/org-transclusion#14]
I want to transclude a heading the same way I refile headings: (de)indenting the transcluded heading also would be great.
This has been [mentioned in the forum](https://org-roam.discourse.group/t/prototype-transclusion-block-reference-with-emacs-org-mode/830/38) as the problem of headings levels
A very good use case of transclusion would be refiling a heading while keeping its contents on the original file via transclusion.
To make this, the destination indendation level and the source _relative_ indentation levels (with respect to the transcluded heading) would have to be added

As an example:

Destination.org
```
#+TITLE: Destination
* Hi all
** [[otc:id:0fa7f97e-eb9c-4dad-b67f-0bb6c766d4b7][I want to transclude in this destination file]]
```

Source.org
```
#+TITLE: Source

* I want to transclude
:PROPERTIES:
:ID:       0fa7f97e-eb9c-4dad-b67f-0bb6c766d4b7
:END:
I will be editing this text soon
** Note what happens if I make a subheading
The problem is the indentation level
** This note is level2 in Source but it should be level3 in Destination
The link is indented 2 lines in Source file + 1 line in Destination file
```

What Destination.org currently looks like after transclusion
```
#+TITLE: Destination
* Hi all
* I want to transclude
:PROPERTIES:
:ID:       0fa7f97e-eb9c-4dad-b67f-0bb6c766d4b7
:END:
I will be editing this text soon
** Note what happens if I make a subheading
The problem is the indentation level
** This note is level2 in Source but it should be level3 in Destination
The link is indented 2 lines in Source file + 1 line in Destination file
```

What I would like Destination.org to look like after transclusion:
```
#+TITLE: Destination
* Hi all
** I want to transclude
:PROPERTIES:
:ID:       0fa7f97e-eb9c-4dad-b67f-0bb6c766d4b7
:END:
I will be editing this text soon
*** Note what happens if I make a subheading
The problem is the indentation level
*** This note is level2 in Source but it should be level3 in Destination
The link is indented 2 lines in Source file + 1 line in Destination file
```

**Comment by nobiot** [comment]
@lytex thank you for the implementation suggestion! 
Didn't think about this way. I don't use archive; perhaps that's why.
I will look into the way archive and capture do this.

**Comment by nobiot** [comment]
I have added an experimental feature for this. I am thinking of touching on it in my next show & tell (Demo No. 4). Thank you again for the suggestion; refill/archive was my blind spot. It might work, though the logic may not be the ideal, and might need a bit more trial and error to make it suitable for transclusions.

**Comment by lytex** [comment]
Wow! Thank you very much! I've just watched your video as well

This feature also allows me to use transclusion as a new kind of "extended refile", which I think is a very powerful concept. Let me explain:

In my [config.el](https://github.com/lytex/doom.d/blob/30b95118cb545b249cbce64adbc77e3644e3e812/config.el#L301-L333) I have a link-and-refile function which allows me to refile a headline to another file while maintaining a link to that headline in the old file (I'm moving that headline to that new file and I'm inserting a link in its place). The destination file can also be a new file, for example when a headline becomes too big and I want to move it to a separated file: this allows me to organically reshape my org files.

Now I can also refile that headline and transclude it onto the old file (the function would be called "transclude-and-refile"). 

What do you think?

**Comment by wuqui** [comment]
Hey, is this supposed to work already? It's not working here, unfortunately:

Having the following in `target.org`, the level-one headings in `source.org` get just inserted as level-one headings, not as level-two headings, as I was hoping for. Am I doing something wrong here?

I'm using the current version and the default of `org-transclusion-use-paste-subtree` is set to `t`.

```
* transcluded stuff
#+transclude: t
[[file:source.org::*heading one]]
```

**Comment by nobiot** [comment]
It's "sort of" working.
The current logic is described in [this section ](https://github.com/nobiot/org-transclusion#merge-different-org-mode-headline-levels) of README.

**Comment by nobiot** [comment]
I will be looking at headline level adjustment for the next update... (At least, that's what I will be focusing on as the first thing for the next show and tell update).

**Comment by wuqui** [comment]
> It's "sort of" working.
> The current logic is described in [this section ](https://github.com/nobiot/org-transclusion#merge-different-org-mode-headline-levels) of README.

Yeah, I think I got the logic, but it's not working for my example. But never mind, it's not urgent, I'll just wait for the next updates.

**Comment by nobiot** [comment]
#39 merged with v0.0.6 main. It comes with a new featuer of adjusting and storing the header level adjustment as :hlevel property on the #+transcude: keyword. I believe this addresses the original issue. Closing. Please advise (re-open or create a new one) if there is still concern. Thank you.

**Comment by SterlingHooten** [comment]
How can you get the :level property to inherit whatever `(org-outline-level)` would return? Right now it seems to require setting it explicitly.

Also is there a way to restore or mimic the ability to use a link after asterisks e.g. `** [[otc:id:0fa7f97e-eb9c-4dad-b67f-0bb6c766d4b7][I want to transclude in this destination file]]`, rather than `#+translcude`? It would be nice to be able to have a syntax that  could mimic the standard org heading, as you could manipulate it in the usual way (moving around and dragging) and the desired heading level would be unambiguous.

**Comment by nobiot** [comment]
> you could manipulate it in the usual way (moving around and dragging) and the desired heading level would be unambiguous

This is an old thread from almost two years ago. With the currently implementation, here are my suggestions. If you wish to discuss further, I suggest that you create a new issue or discussion thread.

#### 1. Use `:only-contents`
Something like this:
```
* Heading 
#+transclude: [[file:bertrand-russell.org::*On Denoting]] :only-contents 
```

#### 2. Use `org-transclusion-make-from-link`
Have a normal link and headline like this below.
```
* [[id:2022-10-10T173507]]
```
While the cursor is on the link, call `C-2 M-x org-transclusion-make-from-link` (`C-2` is an digit-argument, as described in the command's doc string). This will result in this

   ```
* [[id:2022-10-10T173507]]
#+transclude: [[id:2022-10-10T173507]] :level 2
```
With this, you could consider using `org-outline-level` function and create a custom function like this:
```
  (defun my/ot-make ()
    (interactive)
    (let ((level (1+ (org-current-level))))
      (org-transclusion-make-from-link level)))
```
