### ISSUE TITLE
Question: How to tell if point is in a transclusion?

### ISSUE THREAD

**Issue by mgraham** [nobiot/org-transclusion#141]
This is a great package and very well documented!  Thank you!

### Question
I'm trying to make a function that will do the following:
* if point is in a transclusion, call `org-transclusion-move-to-source`
* if point is not in a transclusion, call `org-open-at-point`

How can I tell if point is within a transclusion?

### Background
My use case is that I am using [org-roam](https://www.orgroam.com/) as a knowledge base (so lots of small org files).  Sometimes I have an action item related to an org-roam file.  But I want to keep all my TODO items in a single org file (`todo.org`), so I can centrally manage them.

So I have written a capture hook that puts the TODO item in `todo.org`, creates a link in the org-roam file (using [org-super-links)](https://github.com/toshism/org-super-links), and then transcludes the item back into the org-roam file.  

```
(defun my/org-capture-finalize ()
  (let ((key  (plist-get org-capture-plist :key))
        (desc (plist-get org-capture-plist :description)))
    ;; only do this for the "w" capture template
    (when (and (not org-note-abort) (equal (plist-get org-capture-plist :key) "w"))
      (save-window-excursion
        (org-capture-goto-last-stored)
        (org-super-links-store-link)
        )
      (org-super-links-insert-link) 
      (org-transclusion-make-from-link)
      )))

(add-hook 'org-capture-after-finalize-hook 'my/org-capture-finalize)

```

This works great!

However, when I am on the transcluded TODO item and I press `org-open-at-point`, org finds and follows the backlink in `todo.org` that points back to the org-roam file - so it takes me to the file that I am already in.

What I want to happen is that when point is on the transcluded TODO item, following a link takes me to `todo.org`.   

(And I know I could make separate binding for `org-transclusion-move-to-source`, but I want to use the same binding as I use for following regular org-links.)

**Comment by nobiot** [comment]
Does this work?

```

(defun org-transclusion-within-transclusion-p ()
  "Return t if the current point is within a tranclusion region."

```

**Comment by mgraham** [comment]
Thank you for helping me out, @nobiot, but I don't see the body of the function in your post

**Comment by nobiot** [comment]
It’s part of the package

**Comment by mgraham** [comment]
Oh!  I'm sorry - I misunderstood.  Thank you!  I'll test as soon as I can

**Comment by nobiot** [comment]
No worries. Let me know how you go

**Comment by mgraham** [comment]
Tested, works great!  Thank you!
