### ISSUE TITLE
cannot include property drawer

### ISSUE THREAD

**Issue by pigam** [nobiot/org-transclusion#142]
Hello

I have set `org-transclusion-exclude-elements` to `nil`, but property drawer are not transcluded.

To reproduce: in `/tmp/test.org`
```org
#+TITLE: Fragment

* Test
:PROPERTIES:
:header-args: :var foo=42
:END:

#+begin_src shell
echo $foo
#+end_src
```

In another file:
```org
* I'd like to have a property drawer !
#+transclude [[file:/tmp/fragment.org::*Test]] :level 2
```
I have done : 
```elisp
(setq org-transclusion-exclude-elements nil)
```
Transclusion gives:
```org
* I'd like to have a property drawer !
** Test
#+begin_src shell
echo $foo
#+end_src
```
The property drawer is missing.
How can I include the property drawer ?

Did I miss something in the configuration ?

**Comment by pigam** [comment]
Hmmm, very strange. By setting `org-transclusion-exclude-elements` with the customize interface, it works.

**Comment by nobiot** [comment]
That’s strange. For this variable, sets should just work. Maybe you didn’t evaluate it before adding the transclusion?

**Comment by pigam** [comment]
I restarted emacs, and now it works as intended, sorry.
