### ISSUE TITLE
Expansion of relative to absolute paths of file links in transcluded content

### ISSUE THREAD

**Issue by jtoloe** [nobiot/org-transclusion#145]
I would like to transclude figures generated from babel src blocks. If the generated figure is linked to using a relative path, the transcluded link is relative as well. Would it be possible to include a filter that will expand relative links to absolute ones in the transcluded content? The advantage would be that it would be possible to use relative paths in the source material and still transclude figures and such in documents that are not in the same directory as the source file.

**Comment by nobiot** [comment]
Org-transclude follows the standard link feature of org mode; no translation from/to relative and absolute…. If you prefer use of absolute file name, you should be able to use it. Is this not the case or did I misunderstand what you are after?

**Comment by jtoloe** [comment]
By always using absolute file names there would be no problem, agreed. I use relative file names in links most of the time and am just starting out with org-transclusion. I will not be able to change all my existing links in order to make it work and was thinking about solutions. The idea I had was for a org-transclusion filter that will expand the file names "on the fly". Does it seem like it could work?

The reason I need it is because I want to transclude parts of files (that contain links to image files using relative file names) that are in directories that are different to the one where the file with the transclusion is. Links where the transclusion is will not resolve which means that inline images will not show.

**Comment by nobiot** [comment]
Can you give some example, please

**Comment by jtoloe** [comment]
/home/user/**org**/test.org:

```
* Heading

[[file:test2.org]]
```

/home/user/**org**/test2.org:

```
Could be anything
```

/home/user/**notes**/target.org:

```
#+transclude: [[file:/home/user/org/test.org::* Heading]]
```

Adding the transclusion within `/home/user/notes/target.org` will produce:

```
* Heading

[[file:test2.org]]
```

Following the link to test2.org in target.org will not work since the target of the link is in `/home/user/org/` and not `/home/user/notes/`.

My suggestion is adding a filter such as `:expand-links` so that one would write:

```
#+transclude: [[file:/home/user/org/test.org::* Heading]] :expand-links
```

and get:

```
* Heading

[[file:/home/user/org/test2.org]]
```

**Comment by nobiot** [comment]
Thank you. That makes sense. I need to see what I can do

**Comment by nobiot** [comment]
@jtoloe I have added a new feature as you suggested; a new property `:expand-links` expands relative links to absolute ones per transclusion. It's now merged with the main branch; it will update ELPA-devel overnight (I think). 

It would be great if you could test the latest commit via Git or ELPA-devel. I will wait for a week or so to bump the version to sync with ELPA.

**Comment by nobiot** [comment]
No worries. Thank you for coming back to confirm.

**Comment by stardiviner** [comment]
This `:expand-links` seems not working as I think. It does not correctly expand relative links. Here is the GIF recording shows it.

https://share.cleanshot.com/h0PRj0QG

**Comment by nobiot** [comment]
@stardiviner can you please open a new issue with detail step-by-step guide on how to reproduce the issue? Ideally this should be done with emacs -Q. I can’t have the same configuration you have.

**Comment by stardiviner** [comment]
I posted a new issue here: https://github.com/nobiot/org-transclusion/issues/168

Sorry for late update.
