### ISSUE TITLE
exclude subtrees

### ISSUE THREAD

**Issue by midas0441** [nobiot/org-transclusion#151]
Is it possible to transcluyde a node while excluding all subtrees?

**Comment by nobiot** [comment]
Is this what you are looking to do?

I’m the [manual](https://nobiot.github.io/org-transclusion/#Filter-Org-elements-per-transclusion): 

> 4.4.1 Notes on excluding the headline element

If you add ‘headline’ as a list of elements to exclude, you exclude sub-headlines within your subtrees and you will still transclude the content of the top-most headline of the subtrees.

**Comment by midas0441** [comment]
That's exactly it. Thanks!
