### ISSUE TITLE
Nix fails to build org-transclusion

### ISSUE THREAD

**Issue by TroyFigiel** [nobiot/org-transclusion#154]
I am using Nix and the Emacs-overlay to download my packages from ELPA. Unfortunately, Nix fails to build org-transclusion, because the file [elpa2nix.el](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/emacs/elpa2nix.el) responsible for the build calls the function package-tar-file-info and the tar file on ELPA is missing the org-transclusion-pkg.el.

I am not too familiar with ELPA packaging, so I am not sure whether this is an issue for org-transclusion or for nixpkgs, but I would love to see this work! Any advice is appreciated.

**Comment by nobiot** [comment]
Thank you for reporting. org-transclusion-pkg.el was explicitly listed in .elpaignore file by mistake and my lack of knowledge on what the -pkg.el file was needed for.

I’m on holidays with no laptop, so this was done on a mobile phone with GitHub web UI. Hopefully it goes well with sync with ELPA overnight. The new version 1.3.1 should become available within 24 hours.

Let me know how it goes on your end after ELPA gets updated.

**Comment by TroyFigiel** [comment]
The 1.3.1 build works, so it seems only the org-transclusion-pkg.el metadata was missing. Closing the ticket. Thanks a lot!
