### ISSUE TITLE
Matching highlights with active theme

### ISSUE THREAD

**Issue by oatmealm** [nobiot/org-transclusion#158]
I'm not sure at all if this is possible, but since I noticed that highkighted/marked text is often illegible when a darker theme is active, I was wondering if it'd be possible to add theme rules (per theme, I assume) which will invert the text color and background, or something to this effect... 

Often, in this scenario, the text color is the same as the theme background it's when highlighted. I guess the question is are the faces for the highlights themeable?

**Comment by nobiot** [comment]
Is this an issue for Org-remark, not transclusion?

I am currently on holidays travelling without a PC. I will look when I am back in a few days. What you are looking to do should be possible (in fact, Org-translcusion has some faces defined to do it; you might like to take a look at deffacw code).

**Comment by nobiot** [comment]
Continue with nobiot/orgremark#52
