### ISSUE TITLE
Support `denote:` links

### ISSUE THREAD

**Issue by sthesing** [nobiot/org-transclusion#160]
Hey @nobiot,

thanks for this wonderful package!

Any chance of supporting the `denote:`-links of Prot's [denote](https://github.com/protesilaos/denote) - package?

That would be much appreciated.

**Comment by nobiot** [comment]
Hi @sthesing Thank you for your kind words.
My first gut feel is that I will see what I can add to the documentation. I will unlikely add the code to the code base (but this also depends on the demand). I don't think it will be too challenging. 

It will be something very similar to what @alejandrogallo 
has done [here](https://github.com/nobiot/org-transclusion/issues/159#issue-1519627318).

**Comment by sthesing** [comment]
Thanks for pointing out #159 so me. Sorry that I overlooked that.
Any helpful additions to the documentation would be welcome. I fear my current skills in reading elisp code and knowledge of what's under the hood in custom links is not enough to adapt the work of @alejandrogallo.
So anything helpful on where to start reading would be much appreciated.

**Comment by sthesing** [comment]
> I hope this helps you, you just have to find the `denote-file-path-from-id` functionality in denote
Wow, thanks @alejandrogallo ! With that explanation, it was very easy to set this up. The function in question is called `denote-get-path-by-id`. 
So for anyone who came here looking for a solution: this is the complete code:

```elisp
  (defun denote-org-transclusion-add (link plist)
    (when (string= "denote" (org-element-property :type link))
      (let* ((denote-id (org-element-property :path link))     ;; get denote id from denote:<denote-id> link
             (file-path (denote-get-path-by-id denote-id))     ;; path resolved by the id
             (new-link (with-temp-buffer                       ;; create a [[file:/path/to/denote/note]] org link
                         (insert "file:")                      ;; and store it in 'new-link' variable
                         (insert file-path)
                         (beginning-of-buffer)
                         (org-element-link-parser))))
        (org-transclusion-add-org-file new-link plist))))      ;; re-use the org transclusion infrastructure for file: links
  (cl-pushnew 'denote-org-transclusion-add                     ;; register the org transclusion 'plugin'
              org-transclusion-add-functions)
```

Thanks, @nobiot and @alejandrogallo, this was so very helpful!

**Comment by nobiot** [comment]
@sthesing does the function you have in your last comment work?

I don’t have capacity to follow the discussion now but I can come back to help you if you have not found a function that works. You can keep the issue open if this is the case.

**Comment by sthesing** [comment]
Yes, it works. Thanks a lot!

**Comment by nobiot** [comment]
Great to hear that. @alejandrogallo Thank you :)

**Comment by alejandrogallo** [comment]
@sthesing glad this worked out! Enjoy!

**Comment by ctanas** [comment]
> > I hope this helps you, you just have to find the `denote-file-path-from-id` functionality in denote
> 
> Wow, thanks @alejandrogallo ! With that explanation, it was very easy to set this up. The function in question is called `denote-get-path-by-id`. So for anyone who came here looking for a solution, this is the complete code:
> 
> ```emacs-lisp
>   (defun denote-org-transclusion-add (link plist)
>     (when (string= "denote" (org-element-property :type link))
>       (let* ((denote-id (org-element-property :path link))     ;; get denote id from denote:<denote-id> link
>              (file-path (denote-get-path-by-id denote-id))     ;; path resolved by the id
>              (new-link (with-temp-buffer                       ;; create a [[file:/path/to/denote/note]] org link
>                          (insert "file:")                      ;; and store it in 'new-link' variable
>                          (insert file-path)
>                          (beginning-of-buffer)
>                          (org-element-link-parser))))
>         (org-transclusion-add-org-file new-link plist))))      ;; re-use the org transclusion infrastructure for file: links
>   (cl-pushnew 'denote-org-transclusion-add                     ;; register the org transclusion 'plugin'
>               org-transclusion-add-functions)
> ```
> 
> Thanks, @nobiot and @alejandrogallo, this was so very helpful!
> 
> (Edit: fixed a quoting issue)

I'm not sure I know how to use this function. I've pasted it into init.el, but it's not available after buffer evaluation or start-up (when trying to invoke it with M-x). Maybe I'm doing it wrong?

**Comment by nobiot** [comment]
You don't use this function with M-x. This piece of code does two things: define the function and set the function to a hook. Once this is done, you can use the normal command `org-transclusion-add` (and its friends) while your cursor is on a denote link.

**Comment by ctanas** [comment]
Well, this makes sense. And it works. Thank you!

**Comment by nobiot** [comment]
Good :) I would appreciate it if you could update Reddit and StackOverflow if it is also by you.

**Comment by ctanas** [comment]
Done!

Small issue: works as intended when I add a denote link. But if I save the file and reopen it, invoking 'org-transclusion-add-all' doesn't transclude the denote links, which also appear as inactive (regular text face, not blue, not underlined), as opposed to normal links (file:..) that work just fine (blue and underlines). In the Message buffer I get 'Not transcluded. Continue to next: (void-function denote-get-path-by-id'. But if I hoover the mouse over the denote link and click on it, it opens the file in a new window and then the denote link from the original window becomes blue and underlined and now 'org-transclusion-add-all' work. I am not sure if this is related to the newly defined function, org-transclude, org-mode or denote?

**Comment by stvlm6** [comment]
```elisp
(defun denote-org-transclusion-add (link plist)
  (when (string= "denote" (org-element-property :type link))
    (let* ((denote-full (org-element-property :path link))     ;; get denote id from denote:<denote-full> link
            (denote-parts (string-split denote-full "::"))
            (file-path (denote-get-path-by-id (car denote-parts)))     ;; path resolved by the id
            (new-link (with-temp-buffer                       ;; create a [[file:/path/to/denote/note]] org link
                        (insert "file:")                      ;; and store it in 'new-link' variable
                        (insert file-path)
                        (when (cadr denote-parts)
                          (insert "::" (cadr denote-parts)))
                        (beginning-of-buffer)
                        (org-element-link-parser))))
      (org-transclusion-add-org-file new-link plist))))
```
Tiny modification to include support for [Org headings in Denote](https://protesilaos.com/emacs/denote#h:d99de1fb-b1b7-4a74-8667-575636a4d6a4)

**Comment by codygman** [comment]
The above doesn't support denote org headings with spaces because for raw links `org-element-link-parser` doesn't consider spaces to be valid. It does for angle links, so I added angle brackets to the link in the temporary buffer so spaces are now handled correctly:

```elisp
   (defun denote-org-transclusion-add (link plist)
  (when (string= "denote" (org-element-property :type link))
    (let* ((denote-full (org-element-property :path link))     ;; get denote id from denote:<denote-full> link
            (denote-parts (string-split denote-full "::"))
            (file-path (denote-get-path-by-id (car denote-parts)))     ;; path resolved by the id
            (new-link (with-temp-buffer                       ;; create a [[file:/path/to/denote/note]] org link

                        (insert "<file:")                      ;; and store it in 'new-link' variable
                        (insert file-path)
                        (when (cadr denote-parts)
                          (insert "::" (cadr denote-parts) ">"))
                        (beginning-of-buffer)
                        (org-element-link-parser))))
      (org-transclusion-add-org-file new-link plist))))

  (cl-pushnew 'denote-org-transclusion-add                     ;; register the org transclusion 'plugin'
              org-transclusion-add-functions)
```
