### ISSUE TITLE
Transclusion of LaTeX equations

### ISSUE THREAD

**Issue by vincent-picaud** [nobiot/org-transclusion#164]
Hi, 

I have not found any example of LaTeX equation transclusion. 

Is it possible to do something similar to this ?

```
* One Heading

#+transclude: [[equation]]

* Another Heading

 #+name: equation
\[
   \int \sin{x} dx
\]
```

IMHO, that would be a useful feature (I just want to repeat the equation, not the whole section)

Thank you for this package.

**Comment by vincent-picaud** [comment]
That works, wonderful !
Thank you for your quick answer and sorry for not having been able to find this.

**Comment by nobiot** [comment]
Mo worries :)
