### ISSUE TITLE
line numbering in code block exports

### ISSUE THREAD

**Issue by kpe** [nobiot/org-transclusion#167]
Not sure, if that's the right place to ask this, but:

I cannot figure out, how to enable line numbering (`#+begin_src: lang -n`) when exporting a transclusion (to PDF).
Line numbering without `#+trasclude:` works for me if I append `-n` after the `#+begin_src:`, i.e.

``` md
An example:

#+begin_src: python -n
println("hello")
#+end_src:
```

However, if I try something like:

``` md
An example:

#+transclude: [[file:hello.py]] src: python -n
```

the `-n` will not be preserved in the `#+begin_src:` header.

Is there are way to enforce the line numbering, when a transclusion is exported, or to specify additional arguments (i.e. `-n`) for the `#+begin_src:` line.

**Comment by nobiot** [comment]
I suggest you try adding `:rest "-n"` like this:
```
#+transclude: [[file:hello.py]] src: python :rest "-n"
```

**Comment by nobiot** [comment]
I was hoping that [this section of the user manual](https://nobiot.github.io/org-transclusion/#Transclude-source-file-into-src_002dblock) was clear enough. Please let me know if you have some suggestion for improvement.

**Comment by kpe** [comment]
ohh... sorry, my fault. And thanks! I must have missed that, while reading the docu. It is clearly explained, I just haven't found it.

**Comment by nobiot** [comment]
Please do not worry. I'm genuinely interested in improving discoverability of manual and features available.
