### ISSUE TITLE
property `:expand-links` auto expand link relative path to real absolute path is not right

### ISSUE THREAD

**Issue by stardiviner** [nobiot/org-transclusion#168]
Before enable `org-transclude-mode`, here is the screenshot describe it:

![CleanShot 2023-03-01 at 09 52 02@2x](https://user-images.githubusercontent.com/378699/222024891-045a17e6-f70c-46ef-87ac-8f54cdd4ee72.png)

After enabled `org-transclude-mode`, the link path is expanded but wrong:

![CleanShot 2023-03-01 at 09 56 56@2x](https://user-images.githubusercontent.com/378699/222025581-86dac8da-f216-46a4-b6c6-33b288825784.png)

I added text annotated on image described what it should be.

**Comment by stardiviner** [comment]
Also confirmed emacs -Q also can reproduce this problem.

![CleanShot 2023-03-02 at 19 23 41@2x](https://user-images.githubusercontent.com/378699/222415524-46ddf80a-ede1-4e4f-9fbd-cb33c9712eda.png)

**Comment by nobiot** [comment]
@stardiviner 
I have hard time understanding what the files look like.
Would you mind providing me a set of example files?

At the moment, I have these two filesand don't think they correctly reflect your situation:

- transcluding file: ~/src/org-transclusion/test/168.org
- source file: ~/Org/Beauty/Beauty.org


```org
# transcluding file: ~/src/org-transclusion/test/168.org

#+transclude: [[file:~/Org/Beauty/Beauty.org::#Film Title (1999)]] :expand-links 
```

```org
# source file: ~/Org/Beauty/Beauty.org

* Film Title (1999)
:PROPERTIES:
:CUSTOM_ID: Film Title (1999)
:END:
#+begin_example
[[[[file:~/Org/Beauty/Beauty.org::# Film Title (1999)]]]]
#+end_example
```

**Comment by stardiviner** [comment]
![CleanShot 2023-03-05 at 00 18 54](https://user-images.githubusercontent.com/378699/222917149-f55c0371-faaa-46eb-a97a-dce7a8cbfc75.gif)

You have not noticed the `file:` string between link.

**Comment by stardiviner** [comment]
The problem and fix is here:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/378699/222917460-0b7f3179-2375-4bf1-bda5-28f2ba349cf3.png">

**Comment by nobiot** [comment]
Managed to reproduce the issue. Took time. Thank you for the report and the proposal.
