### ISSUE TITLE
support `denote` type links?

### ISSUE THREAD

**Issue by JonatanSahar** [nobiot/org-transclusion#179]
Hi,
This is a truly awesome package, thank you!
I've recently moved to using denote, and I wondered if there's an easy way to support it. 
denote uses a custom link `[[denote:IDENTIFIER]]`, where the IDENTIFIER is some unique string creaed by denote itself (not an org-id).
I don't understand the inner workings of org enough, so I don't understand how the resolving of such links works, but the documentation says that they are supposed to act as regular `[[file: ... ]]` links would.
Do you have any insight about this?

Thanks!

**Comment by JonatanSahar** [comment]
found https://github.com/nobiot/org-transclusion/issues/160, which seems to answer it. sorry :)

**Comment by nobiot** [comment]
@JonatanSahar , No worries :)
