### ISSUE TITLE
ortr is getting better!

### ISSUE THREAD

**Issue by zenny** [nobiot/org-transclusion#18]
Hi @nobiot :

The only word that popped out from my mouth after watching the fourth video (https://www.youtube.com/watch?v=nO_JEXUeGkI) was WOW, AWESOME! Your approach is so nifty that that the package is getting better every day! :+1:  The look of the transcluded org document was extremely legible.

How did you get the heading numbers on and off in the org document itself? Did you post any emacs.d config?

How does it integrate with org-ref (to include the bibliographic references) and org-roam (to hyperlink the notes with tags)?

However, the headings were not exported properly when you exported `test.org` to plaintext (albeit alright when exported to `pdf` and `docx`). 

Cheers, and stay safe,
/z

**Comment by nobiot** [comment]
Thank you, @zenny!

> How did you get the heading numbers on and off in the org document itself? Did you post any emacs.d config?

I think what you are referring to is [org-superstar-mode](https://github.com/integral-dw/org-superstar-mode). I don't make my config file public -- no argument for or against it; I just don't have it anywhere at the moment.

> However, the headings were not exported properly when you exported test.org to plaintext (albeit alright when exported to pdf and docx).

I will look more carefully; which part is not working correctly?

**Comment by zenny** [comment]
> Thank you, @zenny!
> 
> > How did you get the heading numbers on and off in the org document itself? Did you post any emacs.d config?
> 
> I think what you are referring to is [org-superstar-mode](https://github.com/integral-dw/org-superstar-mode). 

Thanks!

> I don't make my config file public -- no argument for or against it; I just don't have it anywhere at the moment.

No problem, I admire your choice.



> 
> > However, the headings were not exported properly when you exported test.org to plaintext (albeit alright when exported to pdf and docx).
> 
> I will look more carefully; which part is not working correctly?

Look at your screencast between 00:04:38 to 00:04:50 in https://www.youtube.com/watch?v=nO_JEXUeGkI where you exported to org document to the text file (C-c C-e t U), but the heading numbers are incorrectly matched. That is what I was referring to.

**Comment by nobiot** [comment]
Ah, I typed the numbering manually; no trick or code snippet. But I think you can play with `org-num-mode` (I only discovered it yesterday).

I don't use Doom anymore. For my minimal usage, vanilla is a good fit for me. I love the way Doom is done, and use it as a reference for config, etc. It's just too much for me on Windows to sync packages, etc. where I only need 10 or so extra on top of vanilla.

I will look at the export a bit more, but I think ASCII export does some clever thing, and manual typing of number may not be aligned. Thanks for pointing that out 👍

**Comment by nobiot** [comment]
My conifg as of two days ago is pated as a [gist](https://gist.github.com/nobiot/6f7845800a2ecd8c12163b5e270779af), if you would like to see what I am doing. It's already different to today, though ;). I touch it too often.

**Comment by zenny** [comment]
> Ah, I typed the numbering manually; no trick or code snippet. But I think you can play with `org-num-mode` (I only discovered it yesterday).

Thanks for the useful pointer! :+1: 

> 
> I don't use Doom anymore. For my minimal usage, vanilla is a good fit for me. I love the way Doom is done, and use it as a reference for config, etc. It's just too much for me on Windows to sync packages, etc. where I only need 10 or so extra on top of vanilla.

Got it and liked your approach! But I tend to get overwhelmed with the OS you are referring to. ;-)
> 
> I will look at the export a bit more, but I think ASCII export does some clever thing, and manual typing of number may not be aligned; may even replace the manually typed numbering. I did nothing (I don't use Org-export). Thanks for pointing that out +1

My pleasure!

**Comment by zenny** [comment]
> My conifg as of two days ago is pasted as a [gist](https://gist.github.com/nobiot/6f7845800a2ecd8c12163b5e270779af), if you would like to see what I am doing. It's already different to today, though ;). I touch it too often.

I definitely shall have a look at your KISS config!

**Comment by nobiot** [comment]
I'm closing this issue :)
