### ISSUE TITLE
Unable to transclude org-roam files without any headings

### ISSUE THREAD

**Issue by nigo81** [nobiot/org-transclusion#193]
when i  embed a org-roam file without heading:```#+transclude: [[id:c597f234-bf83-48c4-8762-a9706f984891][原子化笔记 Atomic Note]]```,
minibuffer shows error:`No content found with "id:c597f234-bf83-48c4-8762-a9706f984891".  Check the link at point 154, line 9` 
the org-roam file is:
![image](https://github.com/nobiot/org-transclusion/assets/38601513/daeab155-155c-4e6e-b057-c7b87c6e3b08)
After add a header  as below:
![image](https://github.com/nobiot/org-transclusion/assets/38601513/e53862a6-c6d9-4029-adcb-6b61f8a3d372)
It works, and will transclude the information after heading:
![image](https://github.com/nobiot/org-transclusion/assets/38601513/7bae2976-8964-47f5-a6e7-2b57c7ad3c56)

I wan't to know how to transclude a org-roam file without any headings?
Thanks very much.

**Comment by nobiot** [comment]
I suggest you check the value of customizing variable `org-transclusion-include-first-section`. 
It needs to be non-nil. It works on my end.

The variable should be `t` by default. You might be in a much earlier release, when it was `nil` by default -- if so, I'd also suggest to update the package.

**Comment by nigo81** [comment]
> I suggest you check the value of customizing variable `org-transclusion-include-first-section`. It needs to be non-nil. It works on my end.
> 
> The variable should be `t` by default. You might be in a much earlier release, when it was `nil` by default -- if so, I'd also suggest to update the package.

Thanks a lot, I check the `org-transclusion-include-first-section` value is `nil` ,because I set `(setq org-transclusion-include-first-section nil)`, I change it to `t` then works.

But it also include the title of org-roam file,is anyway to transclude text without title?

**Comment by nobiot** [comment]
It is a keyword, so I suggest you try `:exclude-elements` property and exclude “keyword”. User manual [here](https://nobiot.github.io/org-transclusion/#Filter-Org-elements-per-transclusion) .

**Comment by nigo81** [comment]
> :exclude-elements "keyword"

I add `:exclude-elements "keyword title"` and it works ,thanks.

**Comment by nigo81** [comment]
I want to ask a more question.
If i set `org-transclusion-include-first-section` to `t`, and i want to exclude first section before heading,is anyway to achieve it?
Just like the method `:exclude-elements "keyword title"`.

**Comment by nobiot** [comment]
No, the variable is the only way; we have not implemented per-transclusion filter yet. It's a little more complicated than others...

**Comment by nigo81** [comment]
> 

Thanks!
