### ISSUE TITLE
The incompatible with org appear

### ISSUE THREAD

**Issue by vanniuner** [nobiot/org-transclusion#194]
Cause org appear could not expand links within the comments, see [org-appear/issues/18](https://github.com/awth13/org-appear/issues/18). And org-transclusion's sytax is a typically comments. I am wondering that did there have a solution?
```
#+transclude: attendent.sql :lines 15-266

#+transclude: [[./attendent.sql][attendent.sql]] :lines 15-266
```

**Comment by nobiot** [comment]
I don't think we can do much within Org-transclusion. Org-appear has this limitation in README:

> org-appear will fail to detect elements nested inside certain other elements, such as comments or document titles.

Syntactically, `#+transclude` is a [keyword](https://orgmode.org/worg/org-syntax.html#Keywords) (not comment) and it is the same as "document titles" (`#+title`).

**Comment by vanniuner** [comment]
okay,thanks for your reply
