### ISSUE TITLE
Your Emacs config

### ISSUE THREAD

**Issue by fluentpwn** [nobiot/org-transclusion#197]
Hello!

I know this is off-topic, but I couldn't find any other way to contact you. 
What is your emacs config? Especially:
1. What theme are you using?
2. What is the variable pitch font you're using(figure 2)?
3. How did you get mixed pitch working for org-mode? `mixed-pitch` package on MELPA almost does it, but `:PROPERTIES:` and `:END:` are variable-pitch.

**Comment by nobiot** [comment]
1. modus-operandi. It is built-in as if 28.1.
2. The font should be a paid ine called [Concourse](https://mbtype.com/fonts/concourse/) (I think — I change fonts frequently and don’t really remember).
3. I think that Modus themes do it automatically. I don’t do anything. Emacs version may influence this. The image would have been from 28.1 or 29.0.50 (pre-release).

**Comment by fluentpwn** [comment]
> 1. modus-operandi. It is built-in as of 28.1.
> 
>     2. The font should be a paid one called [Concourse](https://mbtype.com/fonts/concourse/) (I think — I change fonts frequently and don’t really remember).
> 
>     3. I think that Modus themes do it automatically. I don’t do anything. Emacs version may influence this. The image would have been from 28.1 or 29.0.50 (pre-release).

Thanks!
For 3, you need a little config - set `modus-themes-mixed-fonts` to true
