### ISSUE TITLE
Has options to Include :PROPERTIES: 

### ISSUE THREAD

**Issue by hyan46** [nobiot/org-transclusion#199]
I have a use case that uses org-transclusion to combine slides from individual sources to make the org-beamer presentation. 
However, the `:PROPERTIES:` is filtered out, which makes it very hard to include beamer col information such as `BEAMER_col`, theorem, etc. 
Is it possible to do the org-transclusion without filtering out these properties. 

```org
*** Illustration :BMCOL:

**** Measure :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.45
:END:
#+attr_latex: :width 0.5 \textheight
[[file:images/2023-08-14_23-03-09_screenshot.png]]

**** Additivity :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.45
:END:
#+ATTR_LATEX: :width 0.5 \textheight
[[file:images/2023-08-14_08-54-16_screenshot.png]]

``` 

becomes 
```org
**** Illustration :BMCOL:

***** Measure :BMCOL:
#+attr_latex: :width 0.5 \textheight
[[file:images/2023-08-14_23-03-09_screenshot.png]]

***** Additivity :BMCOL:
#+attr_latex: :width 0.5 \textheight
[[file:images/2023-08-14_08-54-16_screenshot.png]]
```

**Comment by nobiot** [comment]
Have you tried this customizing option?

https://nobiot.github.io/org-transclusion/#Customizable-filter-to-exclude-certain-Org-elements

**Comment by hyan46** [comment]
Sorry that I didn't realize this option. Should read the manual more carefully. 
After, 
```emacs-lisp
  (setq org-transclusion-exclude-elements nil)
```  
It works perfectly. Thanks!
