### ISSUE TITLE
[Q] What’s the best way to run several other babel cells from another file?

### ISSUE THREAD

**Issue by NightMachinery** [nobiot/org-transclusion#204]
I use noweb references to run a collection of tagged babel cells in a single org file. But I couldn’t get noweb references to work across multiple files. I wonder if org-transclusion can help me?

**Comment by NightMachinery** [comment]
Things seem to work, I just needed to
```
  (setq org-transclusion-exclude-elements nil)
```
to include the properties that set the noweb references. The transclusions being read-only is creating [some problems](https://github.com/emacs-jupyter/jupyter/issues/505) though.

**Comment by nobiot** [comment]
By reading this other problem you referred to, I am not sure if it's an issue of `noweb`. We have had a similar issue with export and nobweb: https://github.com/nobiot/org-transclusion/issues/86.

I do not know how `emacs-jupyter` works, but is there way to wrap it like shown [here](https://github.com/nobiot/org-transclusion/issues/86#issuecomment-896101603)?

**Comment by nobiot** [comment]
Alternatively, if `emacs-jupyter` has some hook, you could perhaps something like this?

```
  (add-hook 'org-export-before-processing-hook
            #'org-transclusion-inhibit-read-only nil t)
```

This is an expert from `org-transclusion` to support export functions of Org.

**Comment by NightMachinery** [comment]
Thanks, excellent! I'll close this issue, as it is mostly an `emacs-jupyter` problem anyway.
