### ISSUE TITLE
[Q/FR] Is there a way to auto-refresh all transclusions in the current buffer?

### ISSUE THREAD

**Issue by NightMachinery** [nobiot/org-transclusion#205]
Is there a way to auto-refresh all transclusions in the current buffer?

I currently have to use `org-transclusion-remove-all` then `org-transclusion-add-all` to refresh all the transclusions. Live sync offers editing, which I don't want (assuming it's buggier than read-only live sync). `org-transclusion-refresh` only refreshes the transclusion at point.

**Comment by nobiot** [comment]
Refresh is just a convenient way to do remove then add (mainly to enable “g” key for refresh when your cursor is in a transition. So what you do is in line with it. I think you can consider a custom function and have a keybinding if you prefer.

**Comment by NightMachinery** [comment]
```
(defun night/org-transclusion-refresh-all ()
      (interactive)
      (org-transclusion-remove-all)
      (org-transclusion-add-all))
```
