### ISSUE TITLE
How to add background to transclusion text

### ISSUE THREAD

**Issue by 101scholar** [nobiot/org-transclusion#222]
In early videos, I saw transclusion text has a colored background. Now the color only activates in live-sync-edit mode. I wonder if it is possible to add colored background in default read-only mode.

I know transclusion text is marked with different fringe color. But when I use olivetti-mode with olivetti-style setting to 'fancy, the fringe disappears. So I wonder if it is possible to make background color instead of fringe color to be different. Thanks.

**Comment by nobiot** [comment]
There should be a face for this. Can you check customize-face, etc. And see if any one of the faces works for your purpose?

**Comment by nobiot** [comment]
Refer to this if you prefer to see the source code: https://github.com/nobiot/org-transclusion/blob/main/org-transclusion.el#L140

**Comment by 101scholar** [comment]
I tried, but when I call describe-face on the transclusion text, no org-transclusion-*-face shows up. I doubt that the face is not activated.

Below is my configuration and screenshot

```
(use-package org-transclusion
  :config
  (require 'org-transclusion-indent-mode))
```

<img width="656" alt="Snipaste_2024-02-19_16-48-07" src="https://github.com/nobiot/org-transclusion/assets/65854870/40bbfb5e-eea3-4607-a030-16cfda19bc68">

**Comment by 101scholar** [comment]
I also tried it with `emacs -Q` in case some other packages overwrites the behavior. But the result is the same and no background color appears after I call `org-transclusion-add`.

**Comment by 101scholar** [comment]
After reading the source code, I guess it is not currently supported? Face org-transclusion behaves like org-transclusion-fringe but in a terminal mode without graphic display. Maybe treat this issue as a feature request for overlay on transclusion text, similar to what is done in live sync edit, such that background color can be customized.

**Comment by nobiot** [comment]
This is the default color (no background visible in graphical user interface). You should be able to customize the color, for example, by customize-face.

**Comment by 101scholar** [comment]
I tried this and set foreground and background to blue

```
(set-face-attribute 'org-transclusion nil :background "#2c4dd1" :foreground "#2c4dd1")
```

but nothing works, same as the screenshot shown above.

**Comment by nobiot** [comment]
It works on my end like this: 

![image](https://github.com/nobiot/org-transclusion/assets/12507865/de216697-ba75-4097-86c2-695561ce8b7f)

**Comment by nobiot** [comment]
```
(custom-set-faces '(org-transclusion ((t (:extend t :background "#ecf7ed")))))
```

**Comment by 101scholar** [comment]
Not working for me.

<img width="456" alt="image" src="https://github.com/nobiot/org-transclusion/assets/65854870/e0b59607-eeb1-478c-b740-f4914cb21c08">

**Comment by 101scholar** [comment]
Here is my emacs information:
+ GNU Emacs 29.1 (build 1, aarch64-apple-darwin22.5.0, Carbon Version 169 AppKit 2299.6) of 2023-08-08
+ Org mode version 9.6.6
+ Org-transclusion 1.3.2

The above screenshot is after executing

```
(custom-set-faces '(org-transclusion ((t (:extend t :background "#ecf7ed")))))
```

and M-x call `org-transclusion-add`.

**Comment by nobiot** [comment]
I guess you are using GNU ELPA, and not GNU-devel ELPA.

This is the fix currently only available with the GNU-devel (http://elpa.gnu.org/devel/). You are probably using the GNU ELPA repo ([NEWS](https://github.com/nobiot/org-transclusion/blob/main/NEWS#L5)):

  - fix: add faces back org-transclusion and org-transclusion-source
    #174

![image](https://github.com/nobiot/org-transclusion/assets/12507865/cf694b9f-da15-48bd-b819-d0af55ba6d9d)

Refer to [installation](https://github.com/nobiot/org-transclusion?tab=readme-ov-file#installation) on README:

- [GNU ELPA](https://elpa.gnu.org/packages/org-transclusion.html) (releases only; equivalent to MELPA-Stable)
- [GNU-devel ELPA](https://elpa.gnu.org/devel/org-transclusion.html) (unreleased development branch; equivalent to MELPA)

**Comment by 101scholar** [comment]
Thanks! it works now.

**Comment by nobiot** [comment]
How do you make it work?

**Comment by 101scholar** [comment]
I read the source code in the github and found it is different from my local source code. So I just realized the install version is GNU ELPA. After I reinstall the GNU-devel ELPA, it works. Thanks for helping me solve this!

**Comment by nobiot** [comment]
Thanks!
