### ISSUE TITLE
Transcluding to a specific headline point in another org file does not work

### ISSUE THREAD

**Issue by lshir** [nobiot/org-transclusion#251]
I use this [syntax](https://stackoverflow.com/a/64808821) to link to a specific header in another org file - by setting `org-link-search-must-match-exact-headline` to `nil`. The linking works fine enough, but the transclusion does not.

e.g. my link looks like `[[file:daily/2024-08-25.org::b774620a-44eb-4d23-886b-fc1e4350a991][Backing up files]]` in the file `20240827180718-backups.org`, and in that file linked to I have a header
```* Backing up files
:PROPERTIES:
:ID:       b774620a-44eb-4d23-886b-fc1e4350a991
:END:
```
but my transclude shows the ID line alone. 
I realize this may be a bit niche but I wonder if this type of flow could be achieved somehow, or if you could propose some alternate way? Thanks

**Comment by lshir** [comment]
linking by `CUSTOM_ID` is an acceptable workaround for my use case, so I don't need this

**Comment by nobiot** [comment]
I'm happy for you to have found a workaround.

But... two comments/questions.

1. `#+transclude: [[id:b774620a-44eb-4d23-886b-fc1e4350a991]]` would just work. Why is this not a solution for you?
2. If you must use `file:` link, you'd need to rely on an advice. This below works on my end.

```
(advice-add #'org-link-search :after #'my/org-link-search-move-to-headline)

(defun my/org-link-search-move-to-headline (&rest _args)
  "Move the point to closest enclosing headline.
This function checks is the point is at keyword element with the
key ID to narrow the scope. Meant to be used as an advice
function in the context of `org-transclusion'."
  (when (string-equal
         (org-element-property :key (org-element-at-point-no-context))
         "ID")
    (org-up-heading-safe)))
```

**Comment by lshir** [comment]
> @lshir
> 
> I'm happy for you to have found a workaround.
> 
> But... two comments/questions.
> 
>     1. `#+transclude: [[id:b774620a-44eb-4d23-886b-fc1e4350a991]]` would just work. Why is this not a solution for you? In a normal circumstance, you don't need to specify a file, because Org-ID will find the ID across files.
> 
>     2. If you must use `file:` link, you'd need to rely on an advice. This below works on my end.
> 
> 
> ```
> (advice-add #'org-link-search :after #'my/org-link-search-move-to-headline)
> 
> (defun my/org-link-search-move-to-headline (&rest _args)
>   "Move the point to closest enclosing headline.
> This function checks is the point is at keyword element with the
> key ID to narrow the scope. Meant to be used as an advice
> function in the context of `org-transclusion'."
>   (when (string-equal
>          (org-element-property :key (org-element-at-point-no-context))
>          "ID")
>     (org-up-heading-safe)))
> ```

Thanks, I didn't realize that `[[id:b774620a-44eb-4d23-886b-fc1e4350a991]]` without the `file:` prefix would work from a _different_ org file but now I have tried and this also does the job. I am not sure which files it checks but I suppose if the ID appears in the org-agenda-files it can be found?

**Comment by nobiot** [comment]
Org Agenda is not relevant. Have a look at document strings of user options `org-id-track-globally` and `org-id-locations-file`.

**Comment by lshir** [comment]
> Org Agenda is not relevant. Have a look at document strings of user options `org-id-track-globally` and `org-id-locations-file`.

Did not know about this! Thanks
