### ISSUE TITLE
`org-transclusion-fringe` does not display in doom emacs

### ISSUE THREAD

**Issue by osheari1** [nobiot/org-transclusion#252]
When settings the fringe variables, the source frindge displays correctly, however the transclusion fringe does not.
```emacs-lisp
(custom-set-faces! '(org-transclusion-fringe
                     :forground "#ebf6fa"
                     :background "#ebf6fa"))
(custom-set-faces! '(org-transclusion-source-fringe
                     :forground "#ebf6fa"
                     :background "#ebf6fa"))
```

In the code below, it seems that the call to overlay-put may be missing?
```emacs-lisp
....
      (overlay-put ov-tc 'line-prefix (org-transclusion-propertize-transclusion))
      (overlay-put ov-tc 'wrap-prefix (org-transclusion-propertize-transclusion))
...
```
https://github.com/nobiot/org-transclusion/blob/main/org-transclusion.el#L1080

![Screenshot_20240910_162628](https://github.com/user-attachments/assets/e566a597-7d7a-48b4-b30a-a6031fa9e952)

**Comment by nobiot** [comment]
@osheari1 , I have spent some time testing the issue.

By the looks of the screen image above, do you have `org-indent-mode` turned on?

Can you check if the issue persists if it is turned off?

I can reproduce the problem only when I have `org-indent-mode` active. And we have a support for it with `org-transclusion-indent-mode`.

On my end, if I activate the `org-transclusion-indent-mode`, the transclusion fringe appears.


![image](https://github.com/user-attachments/assets/90746ef4-9849-4d42-87d4-fc81c02d6283)

**Comment by osheari1** [comment]
Hey, thanks for testing this out. 

I'll test this out as soon as I can. Apologies for the delay, the last few months have been hectic.

**Comment by mkvoya** [comment]
I encountered the same issue, and the `transclusion-indent-mode` works for me.

**Comment by osheari1** [comment]
Thanks for testing this. Will close it out
