### ISSUE TITLE
fdl.texi is not found in the same directory as org-transclusion.texi

### ISSUE THREAD

**Issue by akirak** [nobiot/org-transclusion#255]
Hello,

`org-transclusion.texi` has been added at c33f39988b246ac042c7d3c93d508e56dd074a4f, but it fails to build because `fdl.texi` is not in the same directory (it's in `docs/`):

> org-transclusion.texi:1148: @include: could not find fdl.texi

A fix would probably be to move the texi file to `docs` directory.

**Comment by nobiot** [comment]
Thank you. I think I will follow your advice. As context, see #228

**Comment by akirak** [comment]
Thank you. The issue seems to have been fixed.
