### ISSUE TITLE
Duplicated `#+transclude` line on file save

### ISSUE THREAD

**Issue by jpt4** [nobiot/org-transclusion#257]
Moving from: https://github.com/nobiot/org-transclusion/issues/177

Reporting a related issue: duplication of the #+transclude: <identifier> line when saving a modified file.

To reproduce:

Introduce a transclusion: #+transclude: <identifier>
Add the transclusion, such that the content is now visible in the file.
Modify the file somewhere else, outside of the transclusion.
Save the file.

Result:
The transclusion is removed (content disappears, transclude line remains), a duplicate #+transclude: <etc> line is placed above the original, and an error is reported to the minibuffer: Wrong type argument: number-or-marker-p, nil (This error also shows during other org-transclusion actions, like adding, but does not prevent the action from taking place.)

Software Versions:
Emacs 29.4
org-transclusion 1.4.0

This is new behavior, but I do not know from exactly when. Unfortunately, this makes org-transclusion incompatible with my workflow, though I do endorse the project overall.

Thank you in advance for your attention to this matter.

Trace:
````
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  org-transclusion-keyword-remove()
  org-transclusion-add-payload((:tc-type "org-id" :src-content #("#+begin_20220607Z\nAn alternative index..." 18 202 (:parent (paragraph (:standard-properties ...) #("An alternative indexing scheme for the..." 0 185 ...))) 204 582 (:parent (paragraph (:standard-properties ...) #("Xenotation applies the implexion opera..." 0 378 ...) (superscript ... ...) #("(Z) of the Naturals will generate\nall ..." 0 133 ...))) 583 584 (:parent (superscript (:standard-properties ... :use-brackets-p nil) #("n" 0 1 ...))) 584 716 (:parent (paragraph (:standard-properties ...) #("Xenotation applies the implexion opera..." 0 378 ...) (superscript ... ...) #("(Z) of the Naturals will generate\nall ..." 0 133 ...))) 718 733 (:parent (paragraph (:standard-properties ...) #("C(x) = x/2,  x " 0 15 ...) (verbatim ...) #("1 (mod 2)\n" 0 10 ...))) 764 773 (:parent (paragraph (:standard-properties ...) #("C(x) = x/2,  x " 0 15 ...) (verbatim ...) #("1 (mod 2)\n" 0 10 ...))) 775 843 (:parent (paragraph (:standard-properties ...) #("The Collatz Conjecture states that, gi..." 0 68 ...) (superscript ... ...) #("(x), for all x, there exists a k such ..." 0 44 ...) (superscript ... ...) #("(x) = 1. Furthermore,\nfor all j > k, C" 0 38 ...) (superscript ... ...) #("(x) = {1, 4, 2}, the convergent cycle ..." 0 58 ...))) 844 845 (:parent (superscript (:standard-properties ... :use-brackets-p nil) #("k" 0 1 ...))) 845 889 (:parent (paragraph (:standard-properties ...) #("The Collatz Conjecture states that, gi..." 0 68 ...) (superscript ... ...) #("(x), for all x, there exists a k such ..." 0 44 ...) (superscript ... ...) #("(x) = 1. Furthermore,\nfor all j > k, C" 0 38 ...) (superscript ... ...) #("(x) = {1, 4, 2}, the convergent cycle ..." 0 58 ...))) 890 891 (:parent (superscript (:standard-properties ... :use-brackets-p nil) #("k" 0 1 ...))) 891 929 (:parent (paragraph (:standard-properties ...) #("The Collatz Conjecture states that, gi..." 0 68 ...) (superscript ... ...) #("(x), for all x, there exists a k such ..." 0 44 ...) (superscript ... ...) #("(x) = 1. Furthermore,\nfor all j > k, C" 0 38 ...) (superscript ... ...) #("(x) = {1, 4, 2}, the convergent cycle ..." 0 58 ...))) 930 931 (:parent (superscript (:standard-properties ... :use-brackets-p nil) #("j" 0 1 ...))) ...) :src-buf #<buffer generalized_xenotation.org> :src-beg 1 :src-end 1243) (link (:standard-properties [1 nil 44 66 68 0 nil nil nil nil nil nil nil nil #<killed buffer> nil nil (paragraph (:standard-properties ...))] :type "id" :type-explicit-p t :path "76b3dba9-7aef-4e6f-8e44-dd48c1929582" :format bracket :raw-link "id:76b3dba9-7aef-4e6f-8e44-dd48c192958..." :application nil :search-option nil)) (:link "[[id:76b3dba9-7aef-4e6f-8e44-dd48c1929..." :exclude-elements "drawer keyword" :expand-links ":expand-links" :current-indentation 0) nil)
  org-transclusion-add()
  org-transclusion-after-save-buffer()
  run-hooks(after-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  command-execute(save-buffer)
````

@akashpal-21

**Comment by jpt4** [comment]
To confirm, add the above function in e.g., my init.el, or elsewhere?

**Comment by jpt4** [comment]
eval-last-sexp in *scratch* prints `org-transclusion-keyword-remove` in the minibuffer, but no other values.

**Comment by jpt4** [comment]
Thank you, attempting to reproduce the error results in:

````
(keyword (:standard-properties [8124 8124 nil nil 8236 0 nil nil element t nil nil nil nil #<buffer codex.org> nil nil (special-block (:standard-properties [945 945 957 174898 174909 1 nil nil element t nil nil nil nil #<buff\
er codex.org> nil nil (section (:standard-properties [1 1 1 238729 238729 0 nil first-section element t nil 1 238729 nil #<buffer codex.org> nil nil (org-data (:standard-properties [1 1 1 238729 238729 0 nil org-data nil t ni\
l 88 238729 nil #<buffer codex.org> [org-element-deferred org-element--get-global-node-properties nil t] nil nil] :path "/home/jpt4/codex/codex.org"))]))] :type "Log" :parameters nil))] :key "TRANSCLUDE" :value "[[id:5df5649f\
-23a4-4962-91bd-adb1d61d36b3][Log]] :exclude-elements \"drawer keyword\" :expand-links"))

8124

8236

0

````

**Comment by nobiot** [comment]
Can you let me know your org-version, please?

**Comment by nobiot** [comment]
With the following, I cannot reproduce the issue.

> Introduce a transclusion: #+transclude:
> Add the transclusion, such that the content is now visible in the file.
> Modify the file somewhere else, outside of the transclusion.
> Save the file.

This works as expected and as before. No duplicate `#+transclude` line.

emacs-version: 29.3
org-version: 9.6.15
org-transclusion: 1.4 with the latest commit db09159

**Comment by nobiot** [comment]
I have just tried with what I believe to be the latest stable version of Org -- 9.7.11. I cannot reproduce the issue.

**Comment by nobiot** [comment]
I think the root issue is as described here: https://github.com/org-roam/org-roam/issues/2361#issuecomment-2046910794

Try (package-recompile-all).

This should be another way of what @akashpal-21 did (deleting the eln directory

Here is the key detail:

> (org-element-property :begin link)) still works. But you may have to make sure that the inlined functions are re-compiled. After upgrading
> Org mode, all the users (including org-roam) of Org element API must be re-compiled.

**Comment by jpt4** [comment]
@nobiot, my package versions are as follows:
emacs-org-transclusion  1.4.0                   
emacs-org-roam          2.2.2-1.0b9fcbc         
emacs-org               9.7.11

@akashpal-21, I have deleted .emacs.d/eln-cache, with no change in behavior. Upon saving, the `#+transclude` line is still duplicated. Also, I have noticed another incorrect behavior, which may have been present before: while `org-transclusion-add` works (with the type argument error), `org-transclusion-remove` has no effect, and the only way to remove transcluded content is by modifying and saving the file (which in turn still produces an additional `#+transclude` line).

https://github.com/nobiot/org-transclusion/issues/257#issuecomment-2378939275
@nobiot I am using GuixSD; (package-recompile-all) reports:
````
https://github.com/nobiot/org-transclusion/issues/257#issuecomment-2378939275
````

Thank you both for your assistance thus far.

**Comment by nobiot** [comment]
>  (package-recompile-all) 
> reports:

> https://github.com/nobiot/org-transclusion/issues/257#issuecomment-2378939275

What does this mean? You run (package-recompile-all) and you get the message about GitHub?

This cannot be a correct message for package-recompile-all.

**Comment by nobiot** [comment]
I will assume that this is no longer an issue. Please reopen if this isn't the case.
