### ISSUE TITLE
‘org-transclusion’ isn’t working

### ISSUE THREAD

**Issue by butter-radish** [nobiot/org-transclusion#260]
I hate to be so vague with the title, but ‘org-transclusion’ always errors out and the backtrace is incomprehensible to me.

``` emacs-lisp
(wrong-type-argument integer-or-marker-p nil)
  org-transclusion-content-org-buffer-or-element(t (:link "[[file:20240826193608-find_command.org::Plan 9 fin..." :current-indentation 0))
  org-transclusion-content-org-link((link (:standard-properties [1 nil 54 65 67 0 nil nil nil nil nil nil nil nil #<killed buffer> nil nil (paragraph (:standard-properties [1 1 1 67 67 0 nil top-comment element t nil nil nil nil #<killed buffer> nil nil (section ...)]))] :type "file" :type-explicit-p t :path "20240826193608-find_command.org" :format bracket :raw-link "file:20240826193608-find_command.org::Plan 9 find" :application nil :search-option "Plan 9 find")) (:link "[[file:20240826193608-find_command.org::Plan 9 fin..." :current-indentation 0))
  org-transclusion-add-org-file((link (:standard-properties [1 nil 54 65 67 0 nil nil nil nil nil nil nil nil #<killed buffer> nil nil (paragraph (:standard-properties [1 1 1 67 67 0 nil top-comment element t nil nil nil nil #<killed buffer> nil nil (section ...)]))] :type "file" :type-explicit-p t :path "20240826193608-find_command.org" :format bracket :raw-link "file:20240826193608-find_command.org::Plan 9 find" :application nil :search-option "Plan 9 find")) (:link "[[file:20240826193608-find_command.org::Plan 9 fin..." :current-indentation 0))
  run-hook-with-args-until-success(org-transclusion-add-org-file (link (:standard-properties [1 nil 54 65 67 0 nil nil nil nil nil nil nil nil #<killed buffer> nil nil (paragraph (:standard-properties [1 1 1 67 67 0 nil top-comment element t nil nil nil nil #<killed buffer> nil nil (section ...)]))] :type "file" :type-explicit-p t :path "20240826193608-find_command.org" :format bracket :raw-link "file:20240826193608-find_command.org::Plan 9 find" :application nil :search-option "Plan 9 find")) (:link "[[file:20240826193608-find_command.org::Plan 9 fin..." :current-indentation 0))
  org-transclusion-add()
  org-transclusion-add-all()
  org-transclusion-mode(toggle)
  funcall-interactively(org-transclusion-mode toggle)
  command-execute(org-transclusion-mode record)
  execute-extended-command(nil "org-transclusion-mode" nil)
  funcall-interactively(execute-extended-command nil "org-transclusion-mode" nil)
  command-execute(execute-extended-command)
```

I used ‘C-c l’ to store the link to a named block (“`#+name`”) to generate the transclusion links in question, if it helps.

**Comment by nobiot** [comment]
What you can tell me to help me is more details as below:

- Emacs version
- Org version
- Use of Doom, Spacemacs or any other
- The full link you are trying transclude. The message is truncated: "[[file:20240826193608-find_command.org::Plan 9 fin..."
- Excerpt of the part of the source. You say you have a named block. What are you exactly trying to transclude
- The command you used.

I need to be able to reproduce the error on my laptop, so you need to guide me to do so.

**Comment by nobiot** [comment]
Can you also tell me if other transclusions work and only this one fails? Or none works?

**Comment by nobiot** [comment]
One more thing: Did you recently update your Org from 9.6 to 9.7? And Org-transclusion in your system is older than the new Org 9.7 in your system?

**Comment by butter-radish** [comment]
I’m sorry, 😥 it escaped me to include the following basic details.

- Emacs version: GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) 
- Org mode version: 9.7.11 (N/A @ /gnu/store/f304gcja6dc9b48p3gsbbpnxsgg07pc4-emacs-org-9.7.11/share/emacs/site-lisp/org-9.7.11/) 
- Full link to transcluded object: `[[file:20240826193608-find_command.org::Plan 9 find]]` 
- Transcluded object: (a source block) 
``` org 
#+name: Plan 9 find 
#+begin_src rc 
  grep foo `{du -a | sed 's/^[0-9]*	//'} 
#+end_src 
``` 
- Commands used: `org-transclusion-add` and `org-transclusion-mode` (both fail).

Org-transclusion totally fails, it doesn’t work in any file, and it’s always this same “wrong-type-argument integer-or-marker-p nil” error. This has been happening for a while now (the package isn’t critical for me, so I’ve put off reporting it for a few weeks); I don’t know how old Org 9.7 is, but my best estimate is that this has been going on for the past one or two months at most, so maybe it’s manifested since the 9.7 update?

**Comment by nobiot** [comment]
Thanks for the detail. I suggest you delete all .elc files in org-transclusion directory in your load-path and recompile. You should be able do so by calling (package-recompile-all).

I think the root issue is as described here: org-roam/org-roam#2361 (comment).
