### ISSUE TITLE
Block highlighting too obstructive (for dark themes)

### ISSUE THREAD

**Issue by wuqui** [nobiot/org-transclusion#29]
I'm using Doom Emacs with it's default dark theme and the highlighting of transcluded blocks is way too strong to be pleasant.

<img width="947" alt="transclusion-block-highlighting" src="https://user-images.githubusercontent.com/8737499/99647691-6c719500-2a52-11eb-895a-ca4f995e712a.png">

Since people use all kinds of themes, would it be possible to make the highlighting generally less obstructive?

PS: I'm posting a couple of things here at the same time, hope you know this is meant to be constructive feedback rather than criticism, I'm loving your package already!

**Comment by nobiot** [comment]
Yes, no problem. Thank you. And I know :) because I sometimes switch to a dark theme, and need to change the face manually. 

Do you know how I might be able do this?

I want to do something at a later stage (currently it's only WIP code for the face). But I will need to research first to find a good way.

Thank you for your active feedback, and using it!

**Comment by nobiot** [comment]
I don't know a good way to put both light and dark theme in a package.
The way I adjust the background in my Emacs when I turn on a dark theme is to use the command `set-face-background`...

**Comment by wuqui** [comment]
I see. I was thinking maybe you could use a very simple, non-obtrusive way of marking transcluded sections for know until you're willing and able to deal with this in a more elaborate ways. I don't really have good ideas about how to do this either, unfortunately.
A quick and dirty, low-level solution might be to just insert two lines to mark the start and end of transcluded blocks, e.g.:

```
#<---begin-transclusion--->
#<---end-transclusion----->
```

And maybe there's a proper solution for this that you could steal from an established package. Do you know how org source blocks handle this issue? They have a slightly differently coloured background for blocks, which seems to be adaptive to the current theme and works both with light and dark themes.

**Comment by AlonTzarafi** [comment]
It seems each theme manually adds support for org blocks. The support is wide since org is a built in package.
There aren't a whole lot of packages in emacs that calculate colors based on the current theme. The only one that comes to mind right now is dimmer-mode.

**Comment by nobiot** [comment]
Thank you. I might change the face to just inherit org-block. You can also config the face and save it in your unit.el, too

**Comment by nobiot** [comment]
#39 with v0.0.6 comes with a better default theme; you can switch between light and dark. In addition, if the default is not good, you can always customize the faces to suite your Emacs theme. 

Dark theme default looks like this.
![image](https://user-images.githubusercontent.com/12507865/101285277-982ba380-37e4-11eb-9455-cdf1684f53cd.png)

Closing this issue. Reopen or create another issue if you have further concerns. Thank you!
