### ISSUE TITLE
Useful resources

### ISSUE THREAD

**Issue by lytex** [nobiot/org-transclusion#3]
Glad to know there is more people interested on transclusion!
[alphapapa](https://github.com/alphapapa) is mantaining a  [list of transclusion resources](https://github.com/alphapapa/transclusion-in-emacs) if you didn't know about it (in fact I discovered this repo via alphapapa). Maybe you can get some ideas from here.

**Comment by nobiot** [comment]
@lytex , thank you for you interest and comment. 
Yes, I'm aware of alphapap's repo (I briefly interacted with him on Reddit to ask him to add the link to this repo -- it's working ;)).

This whole prototype is inspired by John Kitchin's idea recorded in alpabapa's repo.
I would not say I have reviewed all the ideas there exhaustively, but I have taken code from StackExchange user Tobias, also listed in the repo. 

I will see how far I can get. So far, I like what I see.

There is a bit more progress than both of the current remote branches show. I'm hoping to merge soon.

**Comment by lytex** [comment]
Ok then, I'm closing the issue
Today I have downloaded org-transclusion and I will be using it and reporting any bugs I find

**Comment by nobiot** [comment]
@lytex , thank you. Really appreciate your trying it out. I'm sure there are many, so please try not to be discouraged at the current state.
