### ISSUE TITLE
does not work with some org files

### ISSUE THREAD

**Issue by cryoguy** [nobiot/org-transclusion#34]
This is a really significant mode.  Thanks for the efforts!    I am having some trouble with some org files (see following). The content does display when is transclusion mode is activated. However, when the transclusion mode is deactivated, the link disappears; and the content is not exported with org-mode export dispatch.  It works with other files so far though.  

The MWE is as follows:

the master org file:

```
#+title: testing
#+transclude: t
[[file:completion_the_org_manual.org][completion]]
```

The referenced org file:
```
#+title: Completion (The Org Manual)
#+Date:2020-11-29 Sun
#+roam_key: https://orgmode.org/manual/Completion.html#Completion
#+roam_alias: org completion
#+roam_tags: "orgmode" completion "Emacs"

[2020-11-29 Sun 20:26] Complete word at point.

~M-Tab~

 At the beginning of an empty headline, complete TODO keywords.

1. After ‘~\~’, complete TeX symbols supported by the exporter.

2. After ‘~:~’ in a headline, complete tags.  Org deduces the list of
  tags from the ‘TAGS’ in-buffer option (see Setting Tags), the
  variable org-tag-alist, or from all tags used in the current buffer.
```

**Comment by cryoguy** [comment]
okay, I know what was the problem. There has to be a headline in the file. but still, it does not have to remove the link when deactivated.

**Comment by nobiot** [comment]
Thank you!

In your particular example, I think  you can include the content by setting this customizing variable to `t`:
`org-transclusion-include-first-section`. This way, the section **before** the first heading can be transcluded; that is, you don't have to have a headline. The variable is set to `nil` by default.

This variable is available in the current main branch (v0.0.5); I would appreciate it if you can try it and let me know how you go.

I agree that attempting an "empty" content should not remove the link. 
The upcoming version (you can preview it in the `feat/meta` branch) should address this particular issue you experienced. 
I will also test your file on my end to ensure that is the case.

**Comment by cryoguy** [comment]
It  works by setting `(setq org-transclusion-include-first-section t)`.  I think it is more useful to create a keyword (`#+`) so it can be applied to a targeted reference, instead of globally.  Maybe the same for the exclusion filters.
Thanks again!  I wish I can help with the code, but I am not fluent in elisp.

**Comment by nobiot** [comment]
oh i see. didn't think about that. thank you. not for the next version, but it looks like the filtering ability for each transclusion with the keyword should be a future consideration. I need to think it through before committing to this feature. Stay tuned ;)

**Comment by cryoguy** [comment]
Thanks. Cool stuff!
