### ISSUE TITLE
what is workaround for a dark theme?

### ISSUE THREAD

**Issue by cryoguy** [nobiot/org-transclusion#35]
so what is a workaround for a dark theme? I am using zenburn.

**Comment by nobiot** [comment]
You can customize the colours with using `org-transclusion-block` and `org-transclusion-source-block`. Try `M-x customize-face` for example. 

Alternatively, you can try the current feature development branch (`feat/meta`). I think I will be able to merge it with the main branch this weekend, or the next (and add a show & tell video).

In the new version (v0.0.6), the default faces will look something like this below.

![image](https://user-images.githubusercontent.com/12507865/100711944-48974300-33b2-11eb-976f-8b3ade1b3a05.png)
*Figure 1*. Dark theme default faces. 

![image](https://user-images.githubusercontent.com/12507865/100711915-3fa67180-33b2-11eb-9c21-a09145b07f14.png)
*Figure 2*. Light theme default faces

**Comment by cryoguy** [comment]
The new version looks nice.  It works for me by setting the face:

```
(custom-set-faces
'(org-transclusion-block ((t (:extend t :background "gray6"))))
 '(org-transclusion-source-block ((t (:extend t :background "#242424"))))
)
```

**Comment by nobiot** [comment]
yeah thanks for trying.  Customising the faces will work in the next version too; I am simply setting the default nicer for both dark and light themes ;)
