### ISSUE TITLE
what is a better way to transclude only the contents under a headline?

### ISSUE THREAD

**Issue by cryoguy** [nobiot/org-transclusion#36]
I want to transclude all the content under a headline, excluding the headline itself though.  what is the right way of doing that?

**Comment by nobiot** [comment]
Hmm. Never thought about this. I tried, but at the moment there does not seem to be a way to exclude the heading only and keep the body like you describe.

You can use dedicated targets, and include only paragraphs. 

Not sure if I can do this easily with the current way via `org-element`. 

Do you know an easy way to separate heading and the section within a headline? Ideally with using `org-element`'s parse tree.

**Comment by cryoguy** [comment]
Some googling leads me [here](https://emacs.stackexchange.com/questions/9492/is-it-possible-to-export-content-of-subtrees-without-their-headings/17677#17677).

```
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
```

**Comment by tgbugs** [comment]
I think you can get the starting point from `:contents-begin` in `org-element`. In terms of how to control it maybe reusing the `:contents-only t` argument from `#+include:` would work.

**Comment by nobiot** [comment]
v0.2.0 has introduced `:only-contents`. Refer to the updated README (usage section). Hope this address this issue. Closing. Let me know if you have questions / issues.  Thank you.
