### ISSUE TITLE
Example Files For Learning

### ISSUE THREAD

**Issue by gluax** [nobiot/org-transclusion#38]
Hey all, I can't this to work no matter how I try it :(. It just eats my transclusion header when I activate or deactivate the mode. I am probably doing something wrong, but I can't understand what's happening in any of the videos. It's hard to understand what's actually happening in the videos as when I try to recreate something off visuals of someone else's formated buffers I don't know if I am recreating the buffer properly due to visual changes. I think an example file would be wonderful.

Below are my files cv.org
```org
#+TITLE: Curriculum Vitae
#+KEYWORDS: vita, CV

#+transclude: t
[[file:common.org][Common Headlines]]

hello
```

common.org
```org
#+AUTHOR: Jonathan Pavlik
#+OPTIONS: toc:nil num:nil
#+STARTUP: entitiespretty
what
```

Should that not work? Why is my transclude section being eaten? Thanks for the help.

**Comment by randomwangran** [comment]
It looks the similar issue as https://github.com/nobiot/org-transclusion/issues/19#issuecomment-735382471

What is your setting with `org-transclusion-include-first-section`?

If you did not set this varible, please add this link to your configuration file, reload it, and do transclusion again.

```elisp
(setq org-transclusion-include-first-section t)
```

**Comment by galuspeed** [comment]
Ah yup that fixed my issue. Sorry didn't see that someone had a similar issue.

**Comment by nobiot** [comment]
@randomwangran , thanks.
In the next version, the code will (should) avoid "eating up" the link like this.
Thank you.

**Comment by nobiot** [comment]
@galuspeed , @randomwangran 
Just for your information. For transcluding the first section (that is, all the text before the first headline), the current version does not apply the filter. To use @galuspeed d 's example:
```
#+AUTHOR: Jonathan Pavlik
#+OPTIONS: toc:nil num:nil
#+STARTUP: entitiespretty
what
```
All the #+AUTHOR, #+OPTIONS, and #+STARTUP keywords are also transcluded. You might like to filter them out (I would).
This filter is coming in the next version -- I put it in the current feature development branch `feat/meta` -- I only lightly tested it, but it seems to work. 

Stay tuned, if this is a feature you might use. 

Thank you.

**Comment by randomwangran** [comment]
Thank you, @nobiot. Works good on my side.

**Comment by randomwangran** [comment]
Solving the issue in https://github.com/nobiot/org-transclusion/issues/22#issue-738128449 as well.

**Comment by nobiot** [comment]
v0.1.0 now merged with the main branch. The new version now does not remove the link / keyword when there is an error in the transluding process (I have changed the program flow). I have also streamlined the syntax now; transclusion is now based only on the `#+transclude:` keyword, which you can generate out of a link. I have also put back a live-sync edit feature as an experiment. You can find more about the new approach and features in the new README.

I would appreciate it you could try the new version and give feedback. Thank you.
