### ISSUE TITLE
Incomplete color value in org-transclusion-block face

### ISSUE THREAD

**Issue by protesilaos** [nobiot/org-transclusion#41]
In light of [issue 1](https://github.com/nobiot/org-transclusion/issues/1), notice an incomplete color value introduced by commit f876e4f565193a5e0e7a3dfaa5a837f72949e148:

```diff
@@ -2,6 +2,6 @@
   '((((class color) (min-colors 88) (background light))
      :background "#efefef" :extend t)
     (((class color) (min-colors 88) (background dark))
-     :foreground "#bfc0c" :background "#1e1e1e" :extend t))
+     :foreground "#bfc0c4" :background "#1e1e1e" :extend t))
   "Face for transcluded block."
   :group 'org-transclusion)
```

Completed it for you.

And thanks for your contributions!

**Comment by nobiot** [comment]
oh thank you! i dont know why it looked like it worked then. i will push a patch.

**Comment by nobiot** [comment]
45e98d fixes the incomplete color value. Thank you!
