### ISSUE TITLE
Only first element is transcluded when transcluding consecutive elements

### ISSUE THREAD

**Issue by lytex** [nobiot/org-transclusion#46]
Having 2 consecutive transcluded elements by id transcludes only the first one:

```
#+transclude: t :hlevel 4
[[id:ae860430-49af-46b5-9007-686ec4ddbeee][Definitions and distinctions]]
#+transclude: t :hlevel 4
[[id:0bb28e25-b8af-4c43-afb0-c96400949742][Flows]]
```

A workaround is to insert three equal signs or any other sequence of characters (a single whitespace works ok for example, but it has to be some text in between):
```
#+transclude: t :hlevel 4
[[id:ae860430-49af-46b5-9007-686ec4ddbeee][Definitions and distinctions]]
===
#+transclude: t :hlevel 4
[[id:0bb28e25-b8af-4c43-afb0-c96400949742][Flows]]
```

https://user-images.githubusercontent.com/32138262/102981448-3f107f00-4509-11eb-8ef9-8b140204d0ee.mp4

**Comment by nobiot** [comment]
I need to come back and look more carefully. I think I needed to prevent the consecutive second one from transcluding.

I always have a blank line between transcluded regions.

Any particular reasons why you would like to have links like this?

**Comment by lytex** [comment]
Ah ok, a blank line also does the same.

It is not a bug, maybe if the README.org has a "gotcha" section, it should go in there

**Comment by nobiot** [comment]
v0.1.0 ([#69](https://github.com/nobiot/org-transclusion/pull/69)) deals with consecutive transclusion without a blank line.
