### ISSUE TITLE
Incompatability with Org-Kanban (and possibly other dynamic block types)

### ISSUE THREAD

**Issue by ykhurshid** [nobiot/org-transclusion#54]
I've noticed that when attempting to transclude a kanban board that is generated by [org-kanban(https://github.com/gizmomogwai/org-kanban), it does not show up. Interestingly, this is only a problem when org-kanban is loaded and when it is not, the generated table shows up just fine.

I have a feeling that this problem may be shared by other dynamic block types but since I don't use those myself, I have yet to test it.

**Comment by nobiot** [comment]
Can you please describe what you do in more detail, a screen capture to illustrate the problem, and/or perhaps give me a sample / test org file to work with? 

I don't use org-kanban, and have no idea what it does even after reading its readme.

I guess I need to understand the relationship between file links that Org-transclusion relies on, and dynamic blocks. How are they combined when used with Org-transclusion?

**Comment by ykhurshid** [comment]
So I am using org-roam and on the left hand side we have a dailies file and the right hand side we have the file containing the board.

![image](https://user-images.githubusercontent.com/40660887/106914044-8a1ed400-66fc-11eb-94e4-7c661eafc9f3.png)

To create the board, I run a command:
![image](https://user-images.githubusercontent.com/40660887/106914387-e08c1280-66fc-11eb-840f-8f62e0ab8101.png)

And voila!

![image](https://user-images.githubusercontent.com/40660887/106914541-07e2df80-66fd-11eb-926f-dcb0a53d1a73.png)

I now name the block "kanban": 

![image](https://user-images.githubusercontent.com/40660887/106914856-56907980-66fd-11eb-9c48-6674b4fbe5b8.png)

However, when I run org-transclusion-mode on the other buffer, this is what I see:

![image](https://user-images.githubusercontent.com/40660887/106915095-9192ad00-66fd-11eb-84fb-d815082eafe3.png)

That is to say, nothing at all. Now interestingly, if I unload the org-kanban library and try this again, this is what I see:

![image](https://user-images.githubusercontent.com/40660887/106915458-ef26f980-66fd-11eb-8afa-d1f397e4ad2f.png)

Aside from the formatting mayhem, it seems to transclude just fine.

**Comment by ykhurshid** [comment]
I realize that this could be a problem unique to org-kanban in which case I might migrate my issue there but there is also the possibility that there is some detail in your implementation of transclusion that precludes the transclusion of dynamic blocks which is why I bring it forward to you for investigation.

**Comment by nobiot** [comment]
Thank you for the screen shots. They helped. I think it's on me.
I just pushed what I believe is a fix 2c09d1e; it's already merged with the main branch.
Would you mind trying it to see if it fixes the kanban issue?

**Comment by ykhurshid** [comment]
Thank you for your work. Very interesting results here. It's still not showing up as long as I have org-kanban loaded but once I unload it, I now get the transcluded kanban board to appear correctly formatted but only if I keep the cursor away from the original buffer.

Here it is displayed correctly:

![image](https://user-images.githubusercontent.com/40660887/106943279-2527a600-671d-11eb-85b8-8447637c8be3.png)

But then it disappears the moment I put my cursor on the source buffer!

![image](https://user-images.githubusercontent.com/40660887/106943433-5902cb80-671d-11eb-92f0-4cb58575a5d3.png)

**Comment by nobiot** [comment]
Yeah disappearing when a cursor is away is by design. 

This is because when you transclude from the same source, the program can still work with a 1-to-1 relationship between the source and target. At the moment, I cannot support 1-to-n (where n is target buffers).

**Comment by nobiot** [comment]
I don't know why loading and unloading of org-kanban ch ages the behaviour, though.

**Comment by ykhurshid** [comment]
> Yeah disappearing when a cursor is away is by design.
> 
> This is because when you transclude from the same source, the program can still work with a 1-to-1 relationship between the source and target. At the moment, I cannot support 1-to-n (where n is target buffers).

That's fair. I don't really think that's a massive usability issue so I will consider that a non-issue.

As for the other problem, I think I'm going to chock that to org-kanban itself and consider my problem solved. I can just set a keybinding to programmatically toggle these functionalities after all. If you feel like this issue should be explored further, feel free to reopen this issue.
