### ISSUE TITLE
org-roam & zettelkasten difference?

### ISSUE THREAD

**Issue by AtomicNess123** [nobiot/org-transclusion#56]
What would be the main differences of this package vs the other two?

**Comment by nobiot** [comment]
Sorry I am not sure what the other two packages you refer to.
Org-roam and Zetteldeft?

Org-transclusion has nothing to do with backlinks that Org-roam enables, the Zettelkasten method, or Deft. 
It enables transclusion, which is defined as the ability to include content from one file into another by reference.
"By reference" in this case is a link.

**Comment by nobiot** [comment]
What was your understanding that prompted you to ask this question?

**Comment by AtomicNess123** [comment]
Thanks for the kind description. I was confused about the purpose, and thought it was doing something similar to org-roam/zetteldeft.

**Comment by nobiot** [comment]
No worries. I see. I use Org-roam daily.
Here is my motivation to write Org-transclusion to help my writing process, and complement the note-taking process Org-roam helps me with.

> I am dabbling in the Zettelkasten method, with using Org-roam. I keep my notes in a repository where my network of notes reside (I guess people call them evergreen, concept, or permanent notes).

> When I start writing something long-form, I want to have a writing project separately from my notes repository, assemble relevant notes to form a basis of the long-form material, and avoid having multiple copies of notes flying around.

> Transclusion should let me do this.

**Comment by AtomicNess123** [comment]
I see. So you want to hace your own writing process outside of where notes live in org-roam, but "linked" to content in your org-roam notes, so it gets updated. Correct me if I'm wrong. Without transclusion, they would live separate. 
I mixed up things also thinking you use both org-roam and zetteldeft (I understand you only use org-roam).

**Comment by nobiot** [comment]
Yes, that is the motivation. At the moment, I have only a small number of notes unrelated to my writing, so not transcluding notes into a writing project. More often, I find myself transcluding different paragraphs between chapters to see where a certain paragraph makes more sense.

I haven't decided whether deft and zetteldeft are good fit for me; still keeping them in my Emacs. I don't use them at the moment, though (I don't have the need for them, probably because my repository is small).

**Comment by AtomicNess123** [comment]
Thanks for your time!
