### ISSUE TITLE
Transclusion of non-org mode files

### ISSUE THREAD

**Issue by mcraveiro** [nobiot/org-transclusion#59]
Hi org-transclusion developers,

thanks very much for an extremely useful mode. As it turns out, it addresses _almost_ precisely a need I have for my own research work [1]. The _almost_ part is that I need it to target regular source code files rather than org-mode files. What I need to do is to link an org-mode file to a region of a (say) C++ source code file. The link needs to be done, ideally, via some identifier which exists in the source code file (say a UUID for instance), and some arbitrary "begin" and "end" markers. For example:

```c++
// {{{ 507ab9d0-d1a5-4fa9-97a9-d78a48a08c3d
<some content>
// }}}
```
I'd like to use org-transclusion to "point to" this region and display it on the org buffer, as well as provide a link to the buffer (as org-transclusion already does, if I understood it right). The link would then be something like this:

```
#+transclude: t
[[file:my_file.cpp#507ab9d0-d1a5-4fa9-97a9-d78a48a08c3d][source code]]
```
For extra bonus points, if it could use the org-babel language source font-locking it would be even more ideal :-) but that is not all that important. Anyway, is this possible? I have been reading through the documentation but I haven't found any thing specific to non-org mode "targets", apologies if I missed it.

Many thanks for your time.

Marco

[1] https://github.com/MASD-Project/dogen

**Comment by mcraveiro** [comment]
It suddenly occurred to me that perhaps the transclusion part is not a hard-requirement for my needs; more of a nice to have. So I'm also trying to see if this is something that can be done using a plain org-mode link [1]. It would, of course, be much nicer with transclusion :-)

[1] https://emacs.stackexchange.com/questions/63391/how-do-i-link-to-an-id-on-a-non-org-mode-file

**Comment by mcraveiro** [comment]
So it appears org-mode supports the basic link above via "text search", which is sufficient for my needs. Still, I'm curious to know your position on transclusion of non org-mode files so I'll leave the ticket open for the moment.

**Comment by nobiot** [comment]
Hi @mcraveiro , thanks for your interest and ideas.

First off, I must say that I'm not coming from programming background, and my original motivation for me to develop this package is to help me with writing (technical writing or qualitative long-form non-fiction material). That has been my primary focus thus far.

I would like to start putting more efforts into features for non-Org text files. Embedding an excerpt from a programming seems to be an interesting feature to start with. As an idea, refer to [this issue](https://github.com/nobiot/org-transclusion/issues/57). 

I would like to work with the default Org Mode link features as much as I can. Usage of `#` might be interesting; it is used by Org files like this: `file:path/to/file.org#custom-id`, but perhaps not in other file extensions.

"Text search" is good for a normal link -- it is enough to determine a single point to jump to. For transclusion, you need two points, beginning and ending points to form a region. So the text search feature cannot be used as is. 

At the moment, I am thinking of starting with a range of lines as indicated in the other issue. This is analogous to Org Mode's `#include:` feature, so I can reuse code from it.

I am currently pressed with a deadline for another part of my life, so I am looking for to coming back to `org-transclusion` in the April/May time frame.

**Comment by nobiot** [comment]
By the way, I use the text search feature to transclude an arbitary paragraph from another Org file, though. 

A paragraph is a unit of text that Emacs recognises (usually delinated by an empty line). The challenge for applying the text search feature for your use case is that the region you would be interested in is unlikely to be a paragraph.

**Comment by mcraveiro** [comment]
Hi @nobiot

> A paragraph is a unit of text that Emacs recognises (usually delinated by an empty line). The challenge for applying the text > search feature for your use case is that the region you would be interested in is unlikely to be a paragraph.

yes I think that would be a problem. This is because the source code will have an arbitrary shape (and length), which will change over time, so we cannot rely on specific formats such as paragraphs and so on. The only thing we can guarantee is the presence of a start and end marker, such as ```{{{``` and ```}}}```.

The problem with the range of lines is that we cannot know the exact range other than by inspecting the file, and it'll change as the user edits the file. However, to be perfectly honest, perhaps a "fixed" range is enough for my purposes. We could simply provide a "preview" of the text content and if the user actually wants to see it, then one must go into the source file. This seems more helpful than just showing the link.

**Comment by nobiot** [comment]
v0.2.1 has been merged into main and includes the following new featuers:

- [Transclude source file into src-block](https://github.com/nobiot/org-transclusion#transclude-source-file-into-src-block)

- [Transclude range of lines for text and source files](https://github.com/nobiot/org-transclusion#transclude-range-of-lines-for-text-and-source-files)

The new version should be able to cover:

> text search based on the GUID/custom ID;
> display the next N lines after the text search.

If you are still using Org-transclusion, I'd appreciate your trying the new features and perhaps giving me feedback. Thank you. Closing for now.
