### ISSUE TITLE
transclusion link wiped out when indented under a headline

### ISSUE THREAD

**Issue by oatmealm** [nobiot/org-transclusion#61]
Don't know if it's by-design or not, but when I move a paragraph level transclusion link under a heading and activate 'transclusion-mode' it gets deleted. Before and after images. In the 2nd screenshot you can see the link has diapered, and it will not show even if I deactivate 'transclusion-mode' (sorry, in Hebrew, if not clear I can use another example).

![gnome-shell-screenshot-HLBB00](https://user-images.githubusercontent.com/68159077/110118382-90b37080-7dba-11eb-82bb-1fa747b8c577.png)

![gnome-shell-screenshot-DM40Z0](https://user-images.githubusercontent.com/68159077/110118436-a7f25e00-7dba-11eb-8e4b-162aa0235055.png)

**Comment by oatmealm** [comment]
Sorry, just realized it happens regardless, even when not under a heading. The second link is removed.

**Comment by nobiot** [comment]
Currently, the link needs to be at the beginning of a line. There is a check coded. For my next update, I am experimenting to remove this. 

It is done in order not to transclude links in the middle of a paragraph. I feel that this is non-requirement since I have introduced `#+transclude` keyword (as part of Org Mode syntax, it needs to be in the beginning of a line).

**Comment by nobiot** [comment]
I am pressed with a deadline from other parts of my life. I am hoping to come back to Org-transclusion and Emacs programming in April / May time frame....

**Comment by oatmealm** [comment]
I understand. It's a wonderful tool. Hope you'll find the time to continue evolving it.

**Comment by nobiot** [comment]
I might push a branch that removes that check only -- there is only one place, one line.

Thank you for your kind comments :)

**Comment by nobiot** [comment]
v0.1.0 (now main branch) streamlined the syntax; the new version has also enabled an experimental live-sync edit function. It would be great if you tried the latest of the main branch. You can find more in the new README.

Now Org-transclusion uses only the `#+transclude:` keyword, which you can generate out of a link. The link does not have to be at the beginning of a line. With this, I am hoping you will not experience the same issue. Closing for now. Please reopen or open a new issue if the problem persists. Thank you.
