### ISSUE TITLE
trouble using ID to transclude from org-roam files

### ISSUE THREAD

**Issue by midas0441** [nobiot/org-transclusion#62]
I am having trouble transcluding with ID links in org-roam files. org-transclude works fine when using an id-link to a header in one of my "regular" org files that belong to org-agenda-files.

I tried two types of ID links in org-roam files, and neither transclude:
1. File-level ID. I have a PROPERTIES drawer at the top of an org-roam file with an ID. 
2. Header-level ID. This is the usual PROPERTIES drawer within a headline. 

All IDs are generated using `org-id`.
I did update `org-id-locations` using `(org-id-update-id-locations '("path/to/my-org-roam/*.org"))`.

Any suggestions?

EDIT:
- even with org-agenda-files, the performance is fickle. The transclusion renders sometimes, and sometimes it doesn't.

**Comment by nobiot** [comment]
Can you navigate to the file with using file-level ID correctly like a normal link and headline ID?

**Comment by midas0441** [comment]
yes, the link is functional in the sense that if I click on them, it opens to the correct buffer.

I better characterized the problem after some testing and restarting emacs.

The following transcludes fine:
1. an ID link to a header in one of my standard org files
2. a FILE link to an org-roam file

The following does not transclude:
- an ID link to an org-roam file that has an ID inside the PROPERTIES drawer at the top of the file.
- an ID link to a header inside an org-roam file

All links are functional in the sense that when I click on them, I am taken to the intended target.

It feels like this has something to do with org-id-locations.

**Comment by midas0441** [comment]
I think I fixed the issue with the following:

(setq myroamfiles (directory-files "~/Dropbox/org/brain" t "org$"))
(org-id-update-id-locations myroamfiles)

**Comment by nobiot** [comment]
Glad that you found a way to fix the issue.
I am not sure why this `(org-id-update-id-locations '("path/to/my-org-roam/*.org"))` didn't work...

Org-transclusion relies on `org-id-find` to find where to get the text from ([source code here](https://github.com/nobiot/org-transclusion/blob/main/org-transclusion.el#L183)).

Judging from your fix, I am guessing that you are using some custom (manual) way to add an ID to the property drawer at the top of a file. I would have thought Org-ID should be able to update the id-locations file during `org-id-get-create`, etc.

**Comment by midas0441** [comment]
The behavior is indeed puzzling to me too. If the link functions (i.e., I can follow it to the intended target), it isn't clear why org-transclusion wouldn't work. Anyway, the code appears to work... even if it is clunky and strange.

**Comment by nobiot** [comment]
Org-roam caches the ID and the target file and advises the Org link navigation to use the cache. This may not be in sync with the org-id-locations file and hash table. What I have observed is that this typically happens when you manually generate or assign an ID to a property---Org-roam cashes the ID and file, but Org-ID does not update the location.
