### ISSUE TITLE
Installing through receipe gives an error

### ISSUE THREAD

**Issue by larebsyed** [nobiot/org-transclusion#63]
I am trying to install on spacemacs as additional package.
I get following error on installation

*receipe*
`(org-transclusion :location (recipe :fetcher github :repo "nobiot/org-transclusion"))`

*error*
```
Saving file /home/larebsyed/.emacs.d/.cache/quelpa/packages/org-transclusion-20210205.215.el...
Wrote /home/larebsyed/.emacs.d/.cache/quelpa/packages/org-transclusion-20210205.215.el
Wrote /home/larebsyed/.emacs.d/.cache/quelpa/packages/org-transclusion-readme.txt
(Spacemacs) Error: 
An error occurred while installing org-transclusion (error: (error Invalid version syntax: ‘20210205.215
’))
```

**Comment by larebsyed** [comment]
Looks like there is an unwanted space at the end of version number generated

**Comment by nobiot** [comment]
Hmm. I have no idea how `quelpa` works. And as far as I know, I don’t generate a version number. 

Is it possible that the name of the branch is “main”, not “master”? You might need to specify the branch name.

Let me know if you can help identify the problem — at the moment, I have no idea. Alternatively, you can simply download the file and evaluate the whole — it’s only a single file.

**Comment by nobiot** [comment]
I haven't heard from you for a while. I am hoping that the issue you reported has been resolved on your end. Closing this issue. Thank you.
