### ISSUE TITLE
Linking to a paragraph with an ID link

### ISSUE THREAD

**Issue by arozbiz** [nobiot/org-transclusion#66]
As I understand it, paragraph transclusions are only available if you use a file link, not an ID link. Would it be possible to change this and allow paragraph transclusion through ID links (e.g., something of the form `id:uuid::dedicated-target`)? Especially with Org-roam moving to an all-ID-based system in v2, this change would have the advantage of making Org-roam pick up paragraph transclusions as backlinks.

**Comment by nobiot** [comment]
@arozbiz Thanks!
I have considered this. My current conclusion is I am not keen.

`id:uuid::dedicated-target` is not part of Org Mode's sytnax. From what I tested now, this format will break both the navigation and Org-roam backlink.

Do you know if this syntax extension is considered upstream with Org Mode?

**Comment by arozbiz** [comment]
That's a good question---I don't know. I'll be honest: I'm a little intimidated by the Org mailing list, especially as someone whose technical abilities are pretty minimal!

**Comment by nobiot** [comment]
@arozbiz 
Have a look at the latest v0.2.0. With the `:only-contents` property, you should be able to achieve “directly linking to paragraphs”. Let me know how you go.
