### ISSUE TITLE
Error in doom emacs: Error.  Link in #+transclude is mandatory at 

### ISSUE THREAD

**Issue by lytex** [nobiot/org-transclusion#71]
I'm getting an error whenever I do any transclusion in doom emacs
The error message is always `Error.  Link in #+transclude is mandatory at <whatever>`

Tested on fresh doom emacs installation to rule out issues with my particular doom config

**Comment by nobiot** [comment]
Thanks. it’s working as expected, by the looks.

I simplified the syntax. You need to have a link as a value of the `#+transclude` keyword like this in a single line. Don’t separate the keyword from the link. 

    #+transclude: t [[file:path/to/file.org::*headline][descrirption]]

Go to the point (e.g. `M-g c`) in the error message and add a link. That will fix the issue.
 
Refer to [Getting Started](https://github.com/nobiot/org-transclusion#getting-started) for a quick tour.

**Comment by nobiot** [comment]
For Doom, there seem to have been another issue #72.
I believe it's been fixed. Perhaps this also changes the behaviour you seen on your end.
Thanks.

**Comment by lytex** [comment]
Hi!
I can confirm that transclusion works fine on my doom setup.

I've made a [bash one-liner ](https://github.com/lytex/doom.d/blob/3e48c37f6e6beadf69b57e803d6d2c282aee353d/utils/org-transclusion.sh)to migrate from the old syntax to the new one (manages transclude and hlevel -> level), feel free to copy or link it in the docs
