### ISSUE TITLE
When Org-ID is not recognized, the error message is cryptic: org-transclusion-add-at-point: Symbol’s function definition is void: nil

### ISSUE THREAD

**Issue by nobiot** [nobiot/org-transclusion#73]

**Comment by nobiot** [comment]
Refer to this: https://github.com/nobiot/org-transclusion/issues/58#issuecomment-835876076
cc @ oatmealm

**Comment by nobiot** [comment]
dadd2a4 adds more useful error message. On Doom, it should look like this:
![2021-05-10_18-58](https://user-images.githubusercontent.com/12507865/117696866-16d8a280-b1c2-11eb-86d1-3dbc5aea7795.png)

**Comment by nobiot** [comment]
`org-id-update-id-locations` updates the mapping between an ID and the file that contains it.

It is stored in the file specified the variable `org-id-locations-file` -- make sure to have the directory. I just looked at Doom and it is under `~/org` which didn't exist, so the file didn't get created correctly. This file is used to keep the ID-file mapping after quiting Emacs.

Org-ID uses this file to create a hash table for quick access when Emacs is up (and Org-ID starts, I think) -- the hash table cannot survive quiting Emacs, hence the need for the file.

Org-roam V1 addtionally adds ID-file mapping in its DB cache. 

Org-transclusion does not rely on Org-roam V1's DB cache, but ONLY on the standard Org-ID way.

**Comment by oatmealm** [comment]
Ok I ran this and I have '.orgids' populated (in dooms cache directory). I've performed again the two steps to create a trnasclusion from an id-link but still the same error about no content being found. I'm not at my computer at the moment but I can send the messages and other info later on if needed.

**Comment by nobiot** [comment]
If  evaluating `(org-id-find "uuid" t)` returns a marker, Org-id is working.

Looking at the screen video you attached, the ID you are trying is for a whole file, and there is only content before the first headline. By default, Org-transclusion does not copy anything before the first section. I think that's the reason why you are now getting the message saying there is no content.

Try setting `org-transclusion-include-first-section` to `t`, or adding a headline with some text in it.

**Comment by oatmealm** [comment]
OK. I've cleared `org-id-locations-file` and ran `(org-id-update-id-locations (list (buffer-file-name (current-buffer))))` from the buffer editing the file I want to transclude. To work on a single file. It seems to work with org-ids only if the there's at least one heading. Even paragraph links ie, `<<text>>` will not work unless they're under a heading... I guess this is by design?

**Comment by oatmealm** [comment]
OK, got it. Did set now `(setq org-transclusion-include-first-section t)` but it seems to bring in also the metadata.... `#+title....`

**Comment by nobiot** [comment]
Yes. That's by design.
Use the filter mechanism to exclude `keyword` (these metadata are keywords).

I suggest to refer to these section of README. The video linked is for an older version, but the part relevant works in the same way.

- https://github.com/nobiot/org-transclusion#customizable-filter-to-exclude-certain-org-elements
- https://github.com/nobiot/org-transclusion#include-the-section-before-the-first-headline-org-file-only

**Comment by oatmealm** [comment]
Thanks, Was just reading about it.  

BTW What about custom faces? Are the transclued sections suppose to be shadowed or something by the theme? I see an overlay but no specific faces to customize. Themes like `modus-*` don't seem to show any ....

```
There is an overlay here:
 From 1849 to 2020
  face                 hl-line
  priority             -50
  window               #<window 3 on מתוך_הספר_בזכות_הצחאבה_מאת_אבן_על_ערבי.org>


There are text properties here:
  :parent              [Show]
  fontified            t
  front-sticky         nil
  line-prefix          [Show]
  local-map            [Show]
  read-only            t
  rear-nonsticky       nil
  tc-beg-mkr           [Show]
  tc-end-mkr           [Show]
  tc-id                "3e374121"
  tc-orig-keyword      (:active-p t :link "[[id:23c60898-ce01-487e-bbc1-66a7997095ed][ע'דיר חם]]")
  tc-pair              #<overlay from 1 to 312 in עדיר_חם_.غدير_خم.org>
  tc-src-beg-mkr       #<marker at 1 in עדיר_חם_.غدير_خم.org>
  tc-type              "org-id"
  wrap-prefix          [Show]
```

**Comment by nobiot** [comment]
I'm still playing with the faces. Look at wrap-prefix and line-prefix. I use fringe bitmaps in this version.
Propertization is done by two functions (one for transclusion, the other for source) so if you want to change it, for now you can either override them with advice or re-define them.

**Comment by oatmealm** [comment]
I'm not sure if there's something still wrong on my side. I'm still getting the message with some links, which I can see their ids in the orgids file, by manually searching it. While  other links work though...
