### ISSUE TITLE
user-error: Error.  Link in #+transclude is mandatory at 6474

### ISSUE THREAD

**Issue by cryoguy** [nobiot/org-transclusion#74]
Getting the following error after recent update. ?

`user-error: Error.  Link in #+transclude is mandatory at 6474`

**Comment by nobiot** [comment]
@cryoguy I thought we had another thread on this? In any case,

The syntax now is this:

```

#+transclude: t [[id:20210501T171427.051019][Bertrand Russell]]

```

No line break.

Please also refer to [Getting Started.](https://github.com/nobiot/org-transclusion).

Let me know if you still struggle and have the same error message.
