### ISSUE TITLE
org-transclusion-live-sync-start-at-point: Wrong type argument: number-or-marker-p, nil Mark set

### ISSUE THREAD

**Issue by cryoguy** [nobiot/org-transclusion#76]
getting the following error when start live-sync edit: ?

`org-transclusion-live-sync-start-at-point: Wrong type argument: number-or-marker-p, nil
Mark set
`

**Comment by nobiot** [comment]
Hi @cryoguy thanks.

This error happens typically when you try live-sync on an Org element that live-sync does not support.
I am assuming there was no change to the buffer; just you just go this error message.

I would like to improve the error message (it was partially done in the latest commit).

I will appreciate it if you can give me a bit more detail on what textual context you called live-sync in and got this message.

Thank you.

**Comment by cryoguy** [comment]
All the links with old id-link stopped working, and I have to regenerate a new link for the link and live-sync to work

**Comment by nobiot** [comment]
Do you use Org-roam and all links point to files in it?

**Comment by nobiot** [comment]
Closing. v0.2.0 has merged with main. I hope it outputs a bit more useful message. Let me know if they persist. Thank you.
