### ISSUE TITLE
link stopped transcluding

### ISSUE THREAD

**Issue by cryoguy** [nobiot/org-transclusion#77]
A link like the following stopped transcluding after recent updates. worked fine before.   ?

`#+transclude: t :hlevel 4 [[file:bibnote/Thurston1970.org::#Thurston1970][NOTES on Calcium-45
uptake]]
`

**Comment by nobiot** [comment]
This a file link with a custom ID.
It works on my end. Can you check if the link without transclusion still works as you expect?

![2021-05-21-issue-77](https://user-images.githubusercontent.com/12507865/119095090-218d0600-ba12-11eb-8d96-042ff305e690.gif)

Side note: :`hlevel` is now `:level` -- please drop "h". Thank you.

**Comment by nobiot** [comment]
Trust that this is no issue now. Closing. Let me know if you have issues. Thank you.
