### ISSUE TITLE
Org transclusion not copying indentation

### ISSUE THREAD

**Issue by arozbiz** [nobiot/org-transclusion#78]
I don't know if this is related to the `org-indent` problem noted in the README, but org-transclusion is not copying over indentation. E.g.:

![image](https://user-images.githubusercontent.com/4499657/119165983-b9dfb680-ba23-11eb-8664-56a3ba094e47.png)

![image](https://user-images.githubusercontent.com/4499657/119165965-b3513f00-ba23-11eb-8e23-8db66e303e17.png)

**Comment by nobiot** [comment]
Hard to tell. Is org-indent-mode on (is the variable t)?

**Comment by arozbiz** [comment]
The previous screenshots were with `org-indent-mode` on. Here is what it looks like with `org-indent-mode` off:

![image](https://user-images.githubusercontent.com/4499657/119234341-0d6d0580-baf3-11eb-8e8c-30a287f90ced.png)

![image](https://user-images.githubusercontent.com/4499657/119234347-1362e680-baf3-11eb-9cde-bd05c5a78568.png)

**Comment by nobiot** [comment]
Looks to me as expected, is it not?

**Comment by arozbiz** [comment]
Sorry, wrong screenshot. Here's the correct set of images.

![image](https://user-images.githubusercontent.com/4499657/119240789-ba597980-bb17-11eb-9ade-84e88a76f8fd.png)

![image](https://user-images.githubusercontent.com/4499657/119240792-c04f5a80-bb17-11eb-8b16-8b4c749a92ea.png)

This is with 'org-indent-mode' off. Two issues:

1. "Item" should be flush with "Test heading", no?
2. "Should be indented" should be indented, but is not.

**Comment by nobiot** [comment]
Thank you. Your screenshot was great help for me to reproduce the issue.

The latest commit [3675040](https://github.com/nobiot/org-transclusion/commit/36750401facb5bc75354627cf5ad0df3cc82725c) should address it.

Note that the user option `org-adapt-indentation` needs to be non-nil for the adaptation of indentation to work.
Refer to the screenshots below.

When `org-adapt-indentation t`
![image](https://user-images.githubusercontent.com/12507865/119256211-e2041c80-bbbf-11eb-9643-89ae1ed09f38.png)

When `org-adapt-indentation nil`
![image](https://user-images.githubusercontent.com/12507865/119256278-3f986900-bbc0-11eb-8316-e9be4b94320f.png)

**Comment by nobiot** [comment]
I believe this issue has been fixed. Let me know if you still have issues and reopen. Thank you.
