### ISSUE TITLE
Emacs hanging on trnasclusion link insertion

### ISSUE THREAD

**Issue by titaniumbones** [nobiot/org-transclusion#9]
Not sure how to diagnose this issue, which is occurring right now with emacs git native-comp  (2 different builds: pure gtk which has xwidget enabled, and vanilla; I  know, that's a lot of modifications). 

when I try to insert an otc link with trnasclusion mode active, emacs cpu usage goes to 100% and I am only able to stop by sending SIGUSR1 or SIGUSR2 signal otthe emacs process.  This sometimes generates the following in backtrac (if xwidget enabled):

```
Debugger entered--entering a function:
* xwidget-webkit-adjust-size-in-frame(#<frame ~/Test-source.org 0x5640b2f44cb0>)
  redisplay_internal\ \(C\ function\)()
  sit-for(0)
  org-insert-link(nil)
  funcall-interactively(org-insert-link nil)
  command-execute(org-insert-link)
```

But since the hang still occurs when xwidget is disabled, I don't think this is the real cause of the problem. I'll keep trying different builds in the hopes that I can help find the problem!

**Comment by nobiot** [comment]
Thank you for trying it out. 
What is this function doing here?
`(org-insert-link)` 
The argument is nil.

**Comment by titaniumbones** [comment]
that's very odd. I am not sure what's going on.  Currently have non-xwidget version installed and am not able to reproduce -- and also need to do some work in Emacs today! -- but will try more soon as I can.

**Comment by titaniumbones** [comment]
was able to trigger this message in the non-xwidget build:
```
coming into #<window 23 on test-source.org>
Error during redisplay: (org-transclusion--toggle-transclusion-when-out-of-focus #<window 23 on test-source.org>) signaled (quit)
```
that's after a freeze, interrupting with SIGUSR1

**Comment by nobiot** [comment]
This means you were moving your focus into test-source.org buffer from another window.
I don't know what this non-xwidget build means, nor SIGUSR1.

Is the build somehow special?

**Comment by titaniumbones** [comment]
ah, sorry.  emacs can be built with or without support for xwidgets (usually used for small instances of webkit browsers running in emacs windows). Arch Linux provides packages that build with various options enabled; some enable xwidgets, others do not.  For reasons I entirely do not understand, sending a signal to the emacs process with `killall emacs -s SIGUSR1` will often interrupt the hang. I do this because it's been recommended to me, not because I really understand what it's doing; but see [this post](https://emacs.stackexchange.com/questions/44085/how-does-emacs-respond-to-unix-signals) for more details. .  In one case where xwidges were enabled, I got the debugger output posted above; in another, I was able to generate the message output I posted just now.

**Comment by nobiot** [comment]
so... both errors are when xwidget is on? Or only the first, and the second non-widget?

I think the first one is a result of some xwidget stuff interfering.

The second... if it happens with a normal build, I would like to know if it is reproducible.

At the moment, I cannot pin down what is happening. My development is entirely on Windows. I have never seen these errors before.

**Comment by nobiot** [comment]
Implemented a new approach. I have removed the toggle features. So this issue should not happen in the new version v0.1.0

I have also put back a live-sync edit feature as an experiment. You can find more about the new approach and features in the new README.

If you are still interested in Org-transclusion, I'd appreciate your trying out the new version and giving any feedback.

Thank you.
