### ISSUE TITLE
Question on `transclude` syntax

### ISSUE THREAD

**Issue by randomwangran** [nobiot/org-transclusion#90]
The biggest thing I miss in the previous version is the format of
the double line to indicate transclusion. I've attached an image
to illustrate.

The benefit is that the user can have a clear view of the title
of that transclusion. In `org-mode` mode, the link is rendered as
a clickable link. Whereas in version 0.2, this feature is no
longer support. The id information is good for the computer, but for
the user, it becomes redundant information.

This is a very bias view, but I still like the previous version.
I am writing this issue to see if it is possible to include a
little bit elisp code to make it possible for a flexible
`transclude` syntax.

![image](https://user-images.githubusercontent.com/8197831/129406285-26f7eaca-2e14-44d2-94df-c756e2bbc4bd.png)

**Comment by nobiot** [comment]
@randomwangran 
Thanks for the discussion.

If I understand your issue correctly, I'd rather try to do this, by applying the org-link face to the link part of the keyword
![image](https://user-images.githubusercontent.com/12507865/129444702-f8867b5d-b0e5-452f-b9a0-834a2feeb031.png).

I would like to avoid supporting the two-line solution from the previous version.

By the way, even with the current way, mouse click seems to work:
![image](https://user-images.githubusercontent.com/12507865/129444738-df1daf89-1336-4946-b5fb-0db863010f18.png)

**Comment by randomwangran** [comment]
Hi @nobiot 

If the two-lines solution brings more trouble, it is not worth going back to the previous version. 

I am trying on the one-line solution.

I found a person (id: jagrg) post a [solution ](https://emacs.stackexchange.com/a/48108/17930)to hide `#+transclude:`, which partially remove some extra information. This can be further improved by making the raw link a regular link, as you shown in the image:

![image](https://user-images.githubusercontent.com/8197831/129589412-3f7b8dad-fcec-4053-bf70-a6458c7b32f7.png)

**Comment by nobiot** [comment]
The [`fix/indent2`](https://github.com/nobiot/org-transclusion/tree/fix/indent2) branch now has the normal Org's link face for the links in `#+transclude` keyword.

![image](https://user-images.githubusercontent.com/12507865/131218692-779eea12-7fb5-44cb-96d3-0bc38194e093.png)

It also adds `org-transclusion-keyword` to change the face of the keyword.

I'd appreciate if you can test branch. 
I'll merge it with main after a little while for testing.

**Comment by nobiot** [comment]
@randomwangran , I merged this change to the main branch at commit ecf8907. Thank you.

**Comment by nobiot** [comment]
Closing with the merge of the feature in the main.
