### ISSUE TITLE
Live sync error on a headline

### ISSUE THREAD

**Issue by alezost** [nobiot/org-transclusion#93]
Hello!

I have an the following `test.org` file
```
* something
Hello.
```

And I transclude it with the following line
```
#+transclude: [[file:test.org]] 
```

Now, if I press `O` (bound to `org-transclusion-move-to-source`) on the
header line of the transcluded file (on ``* something``), I get
``Live sync cannot start here: …`` error.

I see that it comes from `org-transclusion-live-sync-enclosing-element`.
Its docstring says that it is known to work only for some elements.
If I simply add `headline` to the following list:

https://github.com/nobiot/org-transclusion/blob/main/org-transclusion.el#L1414-L1427

I do not have that error and I successfully move to the source file.

So I would like to ask, how can I get rid of that error without
modifying `org-transclusion-live-sync-enclosing-element` function?
Or am I not supposed to do that?

Thank you.

**Comment by nobiot** [comment]
I feel it would be a program error on my part -- pressing "o" should not use live-sync function. At least in theory. Let me look into it.

Thank you for your note.

**Comment by nobiot** [comment]
I merged this fix into the main at ecf8907. I believe this issue has been fixed. Please reopen it if you don't see it fixed yet.

**Comment by alezost** [comment]
I confirm that it is fixed now. Thank you!

**Comment by nobiot** [comment]
@alezost Thank you for confirming :)
